### ISSUE TITLE
Documentation with details

### ISSUE THREAD

**Issue by CoBonF** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#105]
I notice documentation for recipes and block details is missing.
I'd like to know specifically how much weight each block weighs, and also how much weight each ether compressor lifts.

**Comment by djeezuss** [comment]
You can find block's weight <a href="https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/master/src/main/java/ValkyrienWarfareBase/Physics/BlockMass.java">here</a>, but it depends on the block's material.
For the Compressors lift, it is documented in game if I recall correctly.

**Comment by Best108** [comment]
Old issue, closed. I'll add more comments to the code, promise.
