### ISSUE TITLE
[1.11.2] [0.9_alpha] [0.9_pre_2] Unable to respawn

### ISSUE THREAD

**Issue by Renniuq** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#107]
I've been getting this issue for a while, but have been unable to pinpoint an exact cause or method to reproduce for someone else, and so haven't reported it because a vague bug report is a fairly useless bug report. However, I just found [this](http://www.minecraftforum.net/forums/support/server-support/2850056-cant-respawn) and it confirmed both that it is Valk and not just me. Based on this, here's the list of mods in both my pack and that one

- AutoRegLib-1.1-4.jar
- Baubles (they have 1.4.6, I have 1.4.5)
- Biomes 'O Plenty (they have 6.2.0.2254, I have 6.2.0.2267)
- Chameleon-1.11.2-3.1.0.jar
- ImmersiveEngineering-0.11-63.jar
- Mantle-1.11.2-1.2.0.26.jar
- Quark-r1.2-93b.jar
- StorageDrawers-1.11.2-4.2.10.jar
- TConstruct-1.11.2-2.7.1.34.jar
- Valkyrien Warfare 0.9_pre_2.jar (also occured in ValkyrienWarfareRevamped-1.11.2-v0.9_alpha-full.jar)
- Chisels and Bits (they have 13.10, I have 13.13)
- compatlayer-1.11.2-0.2.9.jar
- mysticalagriculture[1.11.2]-1.5.8.jar

I'll test if that list alone recreates the issue and try narrowing, but it doesn't affect all players all the time, 
and tends to impact specific players, even on a server when everyone has the same pack, furthering my confusion and making me more hesitant to post the issue. On one of our worlds, it didn't occur until we set our spawn to a bed on a ship, in another, I hadn't made a ship when it started happening. In my most recent test world, I've been testing out other mods and died and it occured, no spawn point set aside from the normal one. Perhaps that was because Better with mods and its making the player respawn in a random location within a 2 kilometer radius of the base spawn there. My current working theory is that whatever the fix for beds was made the game unhappy if anything else tries to change your spawn, but I'm not really the most well versed in code nuances of the game, so take that with a grain of salt.

As for the specific results, they also varied; they all have the respawn button not functioning, as in, you click it, it will gray out for a moment, nothing happens, and it grays back in, ready to be futilely clicked again. The first time I encountered it (and the most recent), after I set my spawn to a bed placed in the world (a quark bed, white, if it matters), leaving to title and then logging back in would result in a grave where I died, but me being alive, not having died, holding my stuff, near where I just died, like my player data was rolled back but the world wasn't. The other times (and I believe the time the other person encountered it), relogging would result in you still being dead and the world basically ruined and a restarted needed. I really wish I could give a more accurate and helpful description, but I'm afraid that's all I've got right now. I haven't had it happen in an instance where my spawn would be the default spawn for the world, and I feel that is a  key bit of information since the error it throws complains about coordinates, specifically the z one, if I'm reading that right. The console error made when clicking respawn is [here](https://pastebin.com/HLhiT1pu).

Let me know if I can help with more information, I'll do my best. I know rather vague bug reports aren't the most helpful, which is why I try not to make them, but its happened enough and for others now that I figure I should bring the issue to your attention at least.

**Comment by Mattrock607** [comment]
I can confirm this is happening to me also, in single-player. The mods I'm using that Renniuq also has:

AutoRegLib-1.1-4.jar
Baubles 1.4.6
ImmersiveEngineering-0.11-63.jar
Mantle-1.11.2-1.2.0.26.jar
Quark-r1.2-93b.jar
TConstruct-1.11.2-2.7.1.34.jar
ValkyrienWarfareRevamped-1.11.2-v0.9_alpha-full

So it surely must be a conflict with one of those. However, I tested this without TConstruct/ Mantle and without Baubles and the issue still happened, so I think we can safely rule those out. Immersive Engineering and Quark are must-haves IMHO but I'm pretty sure removing one of those would fix the issue. However, I'm playing without Valkyrien currently because like I said, Immersive Engineering and Quark are must-haves for me.

**Comment by Best108** [comment]
Old issue, closed. Although I'll be fixing this by removing my poor attempt at making vanilla beds compatible with ships.
