### ISSUE TITLE
Crash with Just Enough Resources in Mob Drops tab

### ISSUE THREAD

**Issue by dsmall3303** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#108]
Hey there,
There seems to be a nasty crash when your mod is installed alongside Just Enough Resources. Any time you click the "Mob Drops" tab to see what mobs drop what, the client will crash. This happens with any item in the game that has a "Mob Drops" tab.I've verified that this is the problem interaction by disabling Valkyrian Warfare and then opening the last item I was inspecting (wool) in JEI, and found that I did not crash. When I re-enabled the mod and tried again, the crash happened once more.

[I will also be posting this bug to Way2muchnoise](https://github.com/way2muchnoise/JustEnoughResources/issues/122) to see if you guys can figure out a fix. I know Valkyrien Warfare does some special stuff behind the scenes, and I think that having an ability to blacklist certain entities from appearing in JEI might put a bandaid on the problem.

[crash-2017-09-10_18.01.07-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1291066/crash-2017-09-10_18.01.07-client.txt)
[crash-2017-09-10_18.27.07-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1291085/crash-2017-09-10_18.27.07-client.txt)

**Comment by BlueVal** [comment]
Heyo there, 
id like to mention that this is the same case in 1.12.2 (Was a build i picked up yesterday from Curseforge)
Its the exact same issue as described above with the Mob Drops tab in JEI.

[crash-2018-02-04_01.22.21-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1692933/crash-2018-02-04_01.22.21-client.txt)

**Comment by DaMatrix** [comment]
heh, i was just about to close this for being on an outdated version. will look into this.

**Comment by Best108** [comment]
Old issue, closed. VW doesn't ask the chunkloader for tickets anymore.
