### ISSUE TITLE
Crayfish Furniture rendering crash

### ISSUE THREAD

**Issue by Spiderach** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#109]
Running Valkyrien Warfare v0.9_pre1 and CFM 4.1.2 (both MC 1.10.2) on forge version 12.18.3.2488. 
When certain Crayfish blocks use custom rendering (tested on the grill when charcoal is added), the game will crash. This occurs whenever the block in question is rendered.

Not sure if this is something to fix on your end or not, but I've not run into any other incompatabilities with Crayfish whilst building a 1.10 modpack. Thought I'd throw this your way to see if there's a possible fix.
[crash-2017-10-09_15.46.41-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1369796/crash-2017-10-09_15.46.41-client.txt)

**Comment by Best108** [comment]
That is strange, somehow the furniture itself is trying to create an entire ship during the rendering process.

I'll have to find a way to limit the scope of this, so it doesn't happen, will update when I find a fix.

**Comment by DaMatrix** [comment]
OH LOOK HE'S BACK

**Comment by ramiss** [comment]
Hi. We are having the same issue with v1.10.2.  I know you aren't actively working on 1.10.2 but we can't upgrade since other mods we use won't provide higher versions.  Is there ANY workaround or fix you can think of for 1.10.2?

Thanks!

**Comment by Best108** [comment]
Old issue, closed.
