### ISSUE TITLE
Compatibility with OMT mod

### ISSUE THREAD

**Issue by Sunspot0411** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#114]
Hi, I tried the 3.0.0-210 version on a Valkyrien Warfare ship, projectiles do not shoot on target but some unknown direction. Turrets does point on target though, it's just the projectiles do not function well.

**Comment by Sunspot0411** [comment]
Really? No one cares about this issue?

**Comment by DaMatrix** [comment]
Will check out when I get some time.

**Comment by Sunspot0411** [comment]
Thank you!

**Comment by Sunspot0411** [comment]
Just asked the OMT team, they say they can not get VW work on their dev environment, hope you could check this issue also when you have time. Thanks!

**Comment by Sunspot0411** [comment]
@DaMatrix Hello! Did you get a chance to check on this problem? Don't mean to push but it's been a LONG time since I proposed this issue. It should not be a very complicated issue since Alex fixed this issue when VW was in 1.10.2. It's just for some unknown reason this problem comes back after 1.11.

**Comment by DeltaNedas** [comment]
rip why close

**Comment by Sunspot0411** [comment]
this problem is already fixed

**Comment by DeltaNedas** [comment]
wtf it is??? :D
