### ISSUE TITLE
Crash on Ship Build

### ISSUE THREAD

**Issue by TheGameAce** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#118]
Attached my crash log below. Friend is saying that it's a lack of proper implementation of OpenGL Rendering or something of the sort. Version is 1.10.2, release.
[crash-2018-02-01_14.09.56-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1686883/crash-2018-02-01_14.09.56-server.txt)

**Comment by DaMatrix** [comment]
1.10.2 is buggy and unsupported, please update to 1.11.2

**Comment by TheGameAce** [comment]
Ah, that's sad. Was going with 1.10.2 because of other mods, so I won't be able to update right now. Thanks anyhow.
