### ISSUE TITLE
Cannot break blocks on ship while using SpongeForge

### ISSUE THREAD

**Issue by DaMatrix** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#123]
https://i.imgur.com/eghEhvm.gif

**Comment by mainspirit** [comment]
Similar problem.
Do not break the blocks on the ship.
Once installed, the unit remains there.
When you click the left mouse button, it seems to be broken, but if you right-click on this empty space, it appears again. When installing a new block in place of a broken block, the old block appears again.
Version forge-1.12.2-14.23.5.2768-installer-win
Version spongeforge-1.12.2-2768-7.1.4.

**Comment by Best108** [comment]
Old issue, closed. Definitely fixed by now.
