### ISSUE TITLE
Crash on generating chunks

### ISSUE THREAD

**Issue by Angelin01** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#124]
All data can be found here: https://openeye.openmods.info/crashes/5b52da73cf31589ff71a4485354a3646

Apparently there's some stuff related to SpongeForge? I'm not even using that. Anyway, posting it here because Open Eye said VW was likely involved so... Yeah. I'm available for any other info you need.

**Comment by DaMatrix** [comment]
With all those mods, it'd be suprising if it didn't crash. Some mod is modifying the visibility of func_186014_b, I'll fiddle around to see what it might be but it's most likely the fault of whatever mod is making that public.

**Comment by Angelin01** [comment]
I have removed the following mods, yet the crash still occurs. I'll update this comment as I test with more:

- voltz-engine
- icbm-classic
- the-twillight-forest
- optifine
- ice-and-fire
- wizardry
- evilcraft
- dense-metals
- voidcraft
- largeveins

**Comment by Angelin01** [comment]
I'm, dumb, Open Eye will keep the list up to date as long as I launch it (and use the up to date link).
Here is the current crash with the modlist: https://openeye.openmods.info/crashes/a2cc416a324b20e3cbf038407e6e9880

I believe it will keep the link the same now. I have managed to get the game to open with 45 mods only, I'm beggining to narrow it down. I'll bump this thread again once I find the culprit.

**Comment by Angelin01** [comment]
I've found it! It's NotEnoughIDs! Please check [this Open Eye crash log](https://openeye.openmods.info/crashes/1225d7c3691dfd37022ed1c7bd5e295f), it will show that it contains only those mods. I'll make a post on the NotEnoughIDs Github as well. Hopefully I helped.

**Comment by Best108** [comment]
It looks like using @Overwrite on the set method within BlockStateContainer is causing issues, specifically because that mod changes the visibility of the method from protected to public. I'll see if Sponge has any fix for this sort of thing.

**Comment by Best108** [comment]
Fixed in a91f4d07e587879acdac972121d65c898dd3e92d
