### ISSUE TITLE
Crash on Server : Description: Exception in server tick loop

### ISSUE THREAD

**Issue by BlueVal** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#125]
Heyo, another bug i encountered trying Valkyrien Warfare on my dedicated server, this happened with the latest version 

The previous version for 1.12.2 did allow the server to start normally.

[crash-2018-02-05_22.56.25-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1697117/crash-2018-02-05_22.56.25-server.txt)

**Comment by BlueVal** [comment]
Nevermind, didnt read entirely right but this could be a duplicate of #124 ?

**Comment by DaMatrix** [comment]
Definitely is, closing
