### ISSUE TITLE
Incompatibility with NotEnoughIDs

### ISSUE THREAD

**Issue by maxZZzzz** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#127]
Game Crashes during world gen when NotEnoughIDs is installed.
See:
[2018-02-10-7.log](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1713324/2018-02-10-7.log)

**Comment by Best108** [comment]
@maxZZzzz Could you test this again with the latest build? I believe I fixed this issue in the last release.

**Comment by Best108** [comment]
After looking into it further I seem to be in the wrong, I hadn't fixed it in the latest release. Anyways I'm pushing out a commit soon that does fix it.
