### ISSUE TITLE
Minecraft crashes when Plane is in the world

### ISSUE THREAD

**Issue by SirLinkz** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#136]
Hello,
when i'm in the world and a plane too minecraft crashes everytime and when i'm sitting in the plane,
sometimes i get an bluescreen and i can't do anything :( 
Error: https://hastebin.com/qijacugobi.sql

**Comment by SirLinkz** [comment]
I found out when i am on the plane it get s a blue screen and when i destroy a block FROM THE SHIP it gets for 5 seconds normal

**Comment by Best108** [comment]
Old issue, closed.
