### ISSUE TITLE
can't sneak and place levers on 1.12.2 version

### ISSUE THREAD

**Issue by 19PHOBOSS98** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#137]
I tried putting a lever on a dispenser (not physicised) and it just keeps opening up the thing. No matter how I crouch the thing seems to place but despawns immediately after the dispenser inventory shows up... 
I initially thought that it was just another bug from another mod but I singled it out to this mod...
hope you m8s can sort it out
would enjoy it in 1.12.2... :)

**Comment by Best108** [comment]
Old issue, closed. Levers work fine in the latest jenkins.
