### ISSUE TITLE
physics crash with Clayfish Furniture

### ISSUE THREAD

**Issue by GodMorduk** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#138]
https://pastebin.com/Y3s8yiKr

It happens then I place certain blocks into the world, both in single-player and on forge server (not spongeforge). This time it was Christmas tree, but I also noticed it with oven from CFM.

Minecraft 1.12.2, forge 14.23.2.2624.
Valkyrien Warfare version: 0.9 pre3 + HotFix, latest.
CFM version: 4.1.5, also latest (and only one for 1.12 as I can say)

**Comment by Best108** [comment]
Old issue, closed. VW doesn't even bother trying to request chunkloading tickets anymore, we just force it though mixins 😉.
