### ISSUE TITLE
Mod Incompatible With Heavy Inventories Mod

### ISSUE THREAD

**Issue by mzldh** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#141]
Hi, I'm a huge fan of your mod. Great mod! thanks for creating it! it's almost everything I've dreamed of after ships mod in 1.2.5 had died!

When the installed with Heavy Inventories Mod, the only inventory physics mod so far in 1.12, the game will freeze and then crash, whenever any item of Valkyrien's mod shows up in player's inventory slots.

Here is the crash log, and links to Heavy inventories mod along with it's core mod, thank you for your time!

Heavy inventories: https://minecraft.curseforge.com/projects/heavy-inventories?gameCategorySlug=mc-mods&projectID=245768

Super Core: https://minecraft.curseforge.com/projects/supercore

The crash log is here:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw-1.11.6_mc1.12.2.jar)
  TANLoadingPlugin (ToughAsNails-1.12.2-3.1.0.94-universal.jar)
  MixinLoaderForge (Valkyrien+Warfare+0.9_pre_3+[HotFix].jar)
  Inventory Tweaks Coremod ([R键整理]InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/22/18 2:30 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at superscary.heavyinventories.calc.PlayerWeightCalculator.calculateWeight(PlayerWeightCalculator.java:41)
	at superscary.heavyinventories.client.event.ClientEventHandler.onPlayerMove(ClientEventHandler.java:221)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_ClientEventHandler_onPlayerMove_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:364)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at superscary.heavyinventories.calc.PlayerWeightCalculator.calculateWeight(PlayerWeightCalculator.java:41)
	at superscary.heavyinventories.client.event.ClientEventHandler.onPlayerMove(ClientEventHandler.java:221)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_ClientEventHandler_onPlayerMove_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:364)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 844
	Entity Name: 1
	Entity's Exact location: 123.50, 65.00, 252.50
	Entity's Block location: World: (123,65,252), Chunk: (at 11,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@af2e0ea
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5143748832 bytes (4905 MB) / 5762973696 bytes (5496 MB) up to 6442450944 bytes (6144 MB)
	LiteLoader Brand: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
	LiteLoader Mods: none
	LaunchWrapper: 31 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
          - Transformer: $wrapper.toughasnails.asm.transformer.CropDecayTransformer
          - Transformer: $wrapper.toughasnails.asm.transformer.EntityRendererTransformer
          - Transformer: $wrapper.toughasnails.asm.transformer.WorldTransformer
          - Transformer: guichaguri.betterfps.transformers.PatcherTransformer
          - Transformer: guichaguri.betterfps.transformers.MathTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version                  | Source                                      | Signature                                |
	|:--------- |:-------------------- |:------------------------ |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2                   | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp                  | 9.42                     | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.2.2611.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.2.2611             | forge-1.12.2-14.23.2.2611.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mw                   | 1.11.6                   | mw-1.11.6_mc1.12.2.jar                      | None                                     |
	| UCHIJAAAA | valkyrienwarfare     | 0.9_alpha                | Valkyrien+Warfare+0.9_pre_3+[HotFix].jar    | None                                     |
	| UCHIJAAAA | inventorytweaks      | 1.63+release.109.220f184 | [R键整理]InventoryTweaks-1.63.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | waila                | 1.8.23                   | [方块信息]Hwyla-1.8.23-B38_1.12.jar             | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2             | [旅行地图]journeymap-1.12.2-5.5.2.jar           | None                                     |
	| UCHIJAAAA | jei                  | 4.8.5.132                | [物品管理]jei_1.12.2-4.8.5.132.jar              | None                                     |
	| UCHIJAAAA | wailaharvestability  | 1.1.12                   | [采掘信息]WailaHarvestability-mc1.12-1.1.12.jar | None                                     |
	| UCHIJAAAA | mousetweaks          | 2.8                      | [鼠标手势]MouseTweaks-2.8-mc1.12.1.jar          | None                                     |
	| UCHIJAAAA | finite-water-control | 1.0                      | finite-water-control-1.12-1.0.jar           | None                                     |
	| UCHIJAAAA | foamfix              | 0.8.1-1.12               | FoamFixUnofficial-1.12-0.8.1-Lawful.jar     | None                                     |
	| UCHIJAAAA | supercore            | 1.3.1                    | SuperCore+1.12.2-1.3.1.jar                  | None                                     |
	| UCHIJAAAA | heavyinventories     | 2.2.1                    | Heavy+Inventories-1.12.2-2.2.1.jar          | None                                     |
	| UCHIJAAAA | keywizard            | 1.12.2-1.5.3-b1          | keywizard-1.12.2-1.5.3-b1.jar               | None                                     |
	| UCHIJAAAA | toughasnails         | 3.1.0.94                 | ToughAsNails-1.12.2-3.1.0.94-universal.jar  | None                                     |

	Loaded coremods (and transformers): 
weaponlib (mw-1.11.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
TANLoadingPlugin (ToughAsNails-1.12.2-3.1.0.94-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
MixinLoaderForge (Valkyrien+Warfare+0.9_pre_3+[HotFix].jar)
  
Inventory Tweaks Coremod ([R键整理]InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['1'/844, l='新的世界', x=123.50, y=65.00, z=252.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'

Please see this issue to be solved as soon as convenient, thank you!

**Comment by DaMatrix** [comment]
This isn't an issue on our side, but rather some somewhat poor coding on their end. I've reported it to them at https://github.com/SuperScary/Heavy-Inventories/issues/8 . Thanks!
