### ISSUE TITLE
Mod incompatible with flan's mod

### ISSUE THREAD

**Issue by mzldh** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#143]
Hi, Great mod! Hope you're still developing this mod and I hope this issue may be fixed soon.

As we all know and love the Valkyrien Warfare mod is the ideal ship mod we've been dreaming about for years. The ability to walk around and do all sorts of things on the ship like normal Minecraft is amazing.

Ideally, this mod will be the perfect landing platform for vehicles, like being an aircraft carrier for flan's mod warplanes.

**BUT**, as a result of my testing, the entire game will crash if any flan's mod vehicle were placed in the world after installing Valkyrien warfare mod

also, after adding a recipe pack to flans mod will fix the instant crash, but the rendering issue causes the model of the vehicle glitch and shake when driving.(As well as random crashes when playing)

Please have this issue fix as soon as possible, thank you for fulfilling our dream mod!

Here's a link to flan's mod page: http://flansmod.com/

Here is my Crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw-1.11.6_mc1.12.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  MixinLoaderForge (Valkyrien+Warfare+0.9_pre_3+[HotFix].jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 3/31/18 4:53 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.EntityPlane.func_70071_h_(EntityPlane.java:580)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.flansmod.common.driveables.EntityPlane.func_70071_h_(EntityPlane.java:580)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: flansmod:plane (com.flansmod.common.driveables.EntityPlane)
	Entity ID: 52511
	Entity Name: MV-22B Osprey
	Entity's Exact location: 81.50, 5.50, -1077.50
	Entity's Block location: World: (81,5,-1078), Chunk: (at 1,0,10 in 5,-68; contains blocks 80,0,-1088 to 95,255,-1073), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Entity's Momentum: 0.00, -0.05, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/52512, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52513, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52514, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52515, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52516, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52517, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52518, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52519, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52520, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52521, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52522, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52523, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52524, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52525, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52526, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52527, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52528, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52529, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntitySeat['entity.Seat.name'/52530, l='新的世界', x=81.50, y=5.50, z=-1077.50], EntityWheel['entity.Wheel.name'/52531, l='新的世界', x=79.19, y=4.75, z=-1080.19], EntityWheel['entity.Wheel.name'/52532, l='新的世界', x=79.19, y=4.75, z=-1074.81], EntityWheel['entity.Wheel.name'/52533, l='新的世界', x=87.44, y=4.75, z=-1077.50]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: 新的世界
	All players: 1 total; [EntityPlayerMP['mzldh'/19, l='新的世界', x=81.50, y=4.00, z=-1080.50]]
	Chunk stats: ServerChunkCache: 634 Drop: 0
	Level seed: 678969917011992746
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (82,4,-1084), Chunk: (at 2,0,4 in 5,-68; contains blocks 80,0,-1088 to 95,255,-1073), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 274 game time, 274 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30359 (now: false), thunder time: 42432 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5096236328 bytes (4860 MB) / 5702156288 bytes (5438 MB) up to 6442450944 bytes (6144 MB)
	LiteLoader Brand: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
	LiteLoader Mods: none
	LaunchWrapper: 28 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
          - Transformer: guichaguri.betterfps.transformers.PatcherTransformer
          - Transformer: guichaguri.betterfps.transformers.MathTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: pl.asie.foamfix.coremod.FoamFixAT
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: $wrapper.pl.asie.foamfix.coremod.FoamFixTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                 | Version         | Source                                   | Signature                                |
	|:--------- |:------------------ |:--------------- |:---------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft          | 1.12.2          | minecraft.jar                            | None                                     |
	| UCHIJAAAA | mcp                | 9.42            | minecraft.jar                            | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99       | forge-1.12.2-14.23.2.2611.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.2.2611    | forge-1.12.2-14.23.2.2611.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | foamfixcore        | 7.7.4           | minecraft.jar                            | None                                     |
	| UCHIJAAAA | flansmod           | 5.5.2           | Flan's Mod-1.12.2-5.5.2.jar              | None                                     |
	| UCHIJAAAA | flansmodapocalypse | 1.0             | Flan's Mod-1.12.2-5.5.2.jar              | None                                     |
	| UCHIJAAAA | mw                 | 1.11.6          | mw-1.11.6_mc1.12.2.jar                   | None                                     |
	| UCHIJAAAA | valkyrienwarfare   | 0.9_alpha       | Valkyrien+Warfare+0.9_pre_3+[HotFix].jar | None                                     |
	| UCHIJAAAA | controlling        | 3.0.6           | Controlling-3.0.6.jar                    | None                                     |
	| UCHIJAAAA | cqc                | @MOD_VERSION@   | CQC-1.0.0.jar                            | None                                     |
	| UCHIJAAAA | foamfix            | 0.9.4-1.12.2    | FoamFix-1.12.2-0.9.4-Anarchy.jar         | None                                     |
	| UCHIJAAAA | jei                | 4.8.5.138       | jei_1.12.2-4.8.5.138.jar                 | None                                     |
	| UCHIJAAAA | keywizard          | 1.12.2-1.5.3-b1 | keywizard-1.12.2-1.5.3-b1.jar            | None                                     |
	| UCHIJAAAA | mapwriter          | 2.8.2           | MapWriter-1.12.2-2.8.2.jar               | None                                     |

	Loaded coremods (and transformers): 
weaponlib (mw-1.11.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MixinLoaderForge (Valkyrien+Warfare+0.9_pre_3+[HotFix].jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['mzldh'/19, l='新的世界', x=81.50, y=4.00, z=-1080.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'

**Comment by mzldh** [comment]
Note, the entire mod pack gets warped and can no longer load flan's mod vehicles even after deleting the valkyrien warfare mod

**Comment by Best108** [comment]
Old issue, closed. This should be fixed in the latest jenkins builds.
