### ISSUE TITLE
Valkyrien Warfare breaks Astral Sorcery particle effects

### ISSUE THREAD

**Issue by grouNDfx** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#147]
The lighting in the nocturnal powder and the yellow orb from the illumination powder from Astral Sorcery are missing when Valkyrien Warfare and Valkyrie Lib are installed.

Mod Versions:
- Valkyrien Warfare 0.9_alpha
- Valkyrie Lib 1.12.2-2.0.8a
- Astral Sorcery 1.12.2-1.8.5

[debug.log](paste.ee/p/XhD9R)
[latest.log](paste.ee/p/N4E9Z)

**Comment by Best108** [comment]
Old issue, closed.
