### ISSUE TITLE
Enabling particle rendering in configs disables various other particles

### ISSUE THREAD

**Issue by Alan19** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#153]
When particle rendering is enabled, it disables particles such as fire particles from torches and other mods, as well as the particles that appear from falling down. Disabling particle rendering fixes this but it should be fixed so that particles can be rendered on ships.

**Comment by LemADEC** [comment]
What version are you using?
Which other mods are present?

**Comment by Alan19** [comment]
Currently using Forge 14.23.4.2707 and ValkyrienWarfareRevamped-1.12.2-v0.9_alpha-full (1)
  advancedmortars-1.12.2-1.6.20
  AdvancedRocketry-1.12.2-1.4.0-81
  AppleCore-mc1.12.2-3.1.1
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv5-stable-11
  Aroma1997Core-1.12.2-2.0.0.0.b150
  AromaBackup-1.12.2-2.1.1.3.b101
  artisanworktables-1.12.2-1.19.0-SNAPSHOT.6
  astralsorcery-1.12.2-1.8.10
  athenaeum-1.12.2-1.14.0
  AutoRegLib-1.3-17
  base-1.12.2-3.7.2
  Baubles-1.12-1.5.2
  BedBugs-1.12-1.0.1
  BetterAdvancements-1.12.2-0.0.7.42
  BetterBuildersWands-1.12-0.11.1.24569d0d70
  BetterFps-1.4.8
  BetterQuesting-3.5.258
  BiblioCraft[v2.4.3][MC1.12.0]
  BiomesOPlenty-1.12.2-7.0.1.2391-universal
  blockcraftery-0.1.3
  BloodMagic-1.12.2-2.2.12-97
  Bookshelf-1.12.2-2.3.549
  Botania r1.10-354
  ChatFlow-1.4-7
  Chisel-MC1.12.2-0.2.0.31
  chiselsandbits-14.17
  ChunkPregeneratorV1.12-1.8
  CoFHCore-1.12.2-4.5.2.19-universal
  CoFHWorld-1.12.2-1.2.0.5-universal
  ContentTweaker-1.12.2-4.5.0
  Controlling-3.0.6
  CosmeticArmorReworked-1.12.2-v1
  CraftingTweaks_1.12.2-8.1.9
  CraftTweaker2-1.12-4.1.8
  CTM-MC1.12-0.3.0.15
  CustomMainMenu-MC1.12.2-2.0.8
  CustomOreGen-1.12-1.8.1
  cyberware-1.12.2-0.2.10.12
  CyclopsCore-1.12.2-0.11.6
  deepresonance-1.12-1.7.0-alpha
  DimensionalDoors-3.0.9-287
  DrCyanosLootableBodies_1.12-2.4.0
  DungeonTactics-1.12.2-0.14.2
  DynamicSurroundings-1.12.2-3.4.9.13
  ElecCore-1.12.2-1.8.434
  ElectroblobsWizardry-4.1.1-MC1.12.2
  elulib-0.1.12
  EnchantmentDescriptions-1.12.2-1.1.8
  Enchiridion-1.12.2-3.3.3
  EnderCore-1.12.2-0.5.30
  EnderIO-1.12.2-5.0.26
  EnderZoo-1.12.1-1.4.0.49
  Erebus-1.0.22
  EvilCraft-1.12.2-0.10.58
  extraalchemy-0.3.8.4-release
  foamfix-0.9.9.1-1.12.2-anarchy
  forestry_1.12.2-5.8.0.295
  Forgelin-1.6.0
  Guide-API-1.12-2.1.5-60
  Guidebook-1.12.2-2.0.1
  ImmersiveEngineering-0.12-82
  InventoryTweaks-1.64-dev
  IvToolkit-1.3.3-1.12
  jei_1.12.2-4.9.2.196
  jeibees-0.9.0.5-mc1.12.2
  journeymap-1.12.2-5.5.2
  librarianlib-1.12.2-4.9
  LibVulpes-1.12.2-0.2.8-31-universal
  Login_Shield-1.12.2-3-g7c6e7ac
  LootTweaker-1.12.2-0.0.7
  lostcities-1.12-2.0.8
  lostsouls-1.12-1.1.4
  LunatriusCore-1.12.2-1.2.0.42-universal
  MagicBees-1.12.2-3.1.10
  MagnumOpus-1.12.2-0.0.19
  Mantle-1.12-1.3.2.24
  mcjtylib-1.12-3.0.0-alpha
  Mekanism-1.12.2-9.4.10.345
  MekanismGenerators-1.12.2-9.4.10.345
  MetalChests-v1.2.2.g3d3d54b
  modtweaker-4.0.12
  moreoverlays-1.13-mc1.12.1
  Morpheus-1.12-3.3.2
  MTLib-3.0.5
  NaturesCompass-1.12.2-1.5.1
  NetherEx-1.12-2.1.14.15
  NetherPortalFix_1.12.1-5.3.13
  NoFov-MC1.12-1.0.1
  plustic-6.5.2.0
  PrimalCore-1.12.2-0.6.56
  Quark-r1.4-123
  QuickLeafDecay-MC1.12.1-1.2.4
  RecurrentComplex-1.4.7
  RedstoneFlux-1.12-2.0.2.3-universal
  Reliquary-1.12.2-1.3.4.763
  ResourceLoader-MC1.12.1-1.5.3
  ReWIRED-1.0.3
  rockhounding_chemistry-1.12.2-3.13
  rockhounding_core-1.12.2-3.10
  rockhounding_oretiers-1.12.2-3.06
  rockycore-1.12.2-0.4.0
  RoguelikeDungeons-1.12.2-1.8.0
  rustic-1.0.5
  Stackie-1.12.2-1.6.0.48-universal
  StandardExpansion-3.4.143
  TConstruct-1.12.2-2.10.1.84
  tellme-1.12.2-0.6.0
  Thaumcraft-1.12.2-6.1.BETA16
  thaumicperiphery-0.2.3
  TheBetweenlands-3.3.8-universal
  theoneprobe-1.12-1.4.23-alpha
  topaddons-1.12.2-1.7.0
  TrashSlot_1.12.1-8.4.6
  twilightforest-1.12.2-3.7.424-universal
  VTweaks-1.12.2-2.0.0b
  Waystones_1.12.2-4.0.43
  wizardry-0.8.5

**Comment by Best108** [comment]
Old issue, closed. I think I've fixed this already.
