### ISSUE TITLE
[Suggestion] Spacific designed Ocean ship physics

### ISSUE THREAD

**Issue by mzldh** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#155]
Please consider to make a spacific designed physics function for a surface Ocean ship instead of air ship. It would make the mod more complete. 
Again, thank you for creating such a great mod! :)

**Comment by Rubyjunk** [comment]
Thank you so much for your report. We have been continuing this issue in #223, which you may follow if you're interested. 

With <3,
Valkyrien Warfare Team
