### ISSUE TITLE
Break blocks from really far away

### ISSUE THREAD

**Issue by E-daw** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#157]
![2018-05-26_15 04 43](https://user-images.githubusercontent.com/34014927/40579824-5964f826-60f6-11e8-8400-eae77b3c2f30.png)
![2018-05-26_15 04 45](https://user-images.githubusercontent.com/34014927/40579825-597367da-60f6-11e8-92ef-115b8a894797.png)

I don't know if it is even this mod that's causing it, but ever since I started using it, I've been able to interact with blocks the are really far away.

**Comment by LightningSh0ck** [comment]
remove VW and try again. Also is this a huge ship or just the world?

**Comment by Best108** [comment]
I have released build 0.9_prerelease_5 which fixes this bug. As such I am closing the issue for now.
