### ISSUE TITLE
can't load with dev-environment

### ISSUE THREAD

**Issue by Sunspot0411** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#158]
I'm trying to create a cannon mod for VW but cannot load VW mod  with the develop environment, it causes the game to quit with description: 

Exception in thread "main" 
Process finished with exit code 1

**Comment by LightningSh0ck** [comment]
place normal copy of the mod(*-full.jar) in run/mods

**Comment by Sunspot0411** [comment]
it does not work, the client won't start if i have vw in the mods file and says "Process finished with exit code 1"

**Comment by Sunspot0411** [comment]
OK, now i think this is not a problem with div-environment but a compatibility issue with forge
https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/159

**Comment by LightningSh0ck** [comment]
use the same version of forge and MCP of VW.

**Comment by Sunspot0411** [comment]
OK, now I tried it with the same version of forge, it still cannot load vw. I do think vw needs a div version so that others could make their mods compatible with vw.

**Comment by Sunspot0411** [comment]
Actually OMT group tried to make their mod compatible with vw but they cannot load vw in their div-environment so they temporally give up on that ide.

**Comment by Best108** [comment]
Fixed in c1031a5fdc9319a9834c880c6c79905fe29313e9
