### ISSUE TITLE
Snow forming at low altitude inside ship

### ISSUE THREAD

**Issue by LemADEC** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#160]
As of 0.9_prerelease_5, snow is forming on the ship while it's raining and the ship is at ocean level.
In vanilla, snow would only form if the block is high enough in a cold biome.

![image](https://user-images.githubusercontent.com/4776032/41203089-e3d5ffa4-6cd2-11e8-8b01-7e0f151a3166.png)

**Comment by Best108** [comment]
Fixed in the shown commit.
