### ISSUE TITLE
When Valkyrien Warfare is installed alongside Cyclic, the Cyclic Rainbow Cannon's projectile holds still instead of flying.

### ISSUE THREAD

**Issue by TeetoKaziim** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#171]
Minecraft version & Mod List:

Minecraft: 1.12.2
Forge: 14.23.4.2708
Cyclic: 1.15.11
Valkyrien Warfare: 0.9_prerelease_5[Optimization update]

Describe problem (what you were doing / what happened):
In singleplayer, when Valkyrien Warfare and Cyclic is installed, Cyclic's Rainbow Cannon, when fired, the projectile hangs in the air instead of flying forward.

This is a cross-post from their issue tracker, since I don't know whoms'es "fault" this is, and am hopeful to promote cooperation and harmony!

https://github.com/PrinceOfAmber/Cyclic/issues/851

Thanks for the time out of your day :D

**Comment by PrinceOfAmber** [comment]
Hi, im cyclic dev.

I didnt see anything in latest.log when i tested it out.


Here is my entity movement code, it works in isolation and with other mods installed  (tinkers and so on)  

https://github.com/PrinceOfAmber/Cyclic/blob/c7edb436d41868a015254d219c8909c45e5be6ea/src/main/java/com/lothrazar/cyclicmagic/item/cannon/EntityGolemLaser.java#L123

**Comment by Lothrazar** [comment]
Is this mod abandoned?

**Comment by DaMatrix** [comment]
no, but @Best108 is busy with university stuff most of the time, and i don't know math or physics well enough to understand how the core of the mod works (i mainly do code quality improvements). so it's generally idle in development, except when Best108 is on a break from school.

at any rate the majority of the mod is being rewritten atm, so we're not bothering with bugfixes until we have it back to a totally functional state.

**Comment by Best108** [comment]
Old issue, closed. Hopefully this is fixed in the latest version.
