### ISSUE TITLE
Request: Config option to disable etherium ore generation

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#173]
To make mining more interesting in my pack I'm using CoFH World to force etherium ore to generate only on the tops of caves. I want to move all ore generation to CoFH World so I can control it easier.

I noticed that there's no config option to disable the mod's default ore generation. Can this be added? Almost all mods that add ores have a setting like this.

**Comment by Best108** [comment]
Old issue, closed. Added to config.
