### ISSUE TITLE
crashed on startup

### ISSUE THREAD

**Issue by matyklugDebbuged** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#176]
valkyrien warfare: 293
+optifine d3
+vannila fix 1.0.8

**Comment by LemADEC** [comment]
Build 293 is bugged, use an older one for now

**Comment by DaMatrix** [comment]
Please send the crash report+logs or we can't help with this

**Comment by Pirog17000** [comment]
crashing (server) if I'm trying to load with latest version from Jenkins (293)
https://pastebin.com/h83ccX3z

**Comment by Best108** [comment]
Old issue, closed. This should already be fixed.
