### ISSUE TITLE
My inventory keeps filling with stuff

### ISSUE THREAD

**Issue by Pirog17000** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#177]
When I fly around on any ship, my inventory keeps filling with stuff - 
**plants and eggs from two mods:  Dynamic Trees and Exotic Birds**
even if I hover on one place, it keeps filling.

https://cdn.discordapp.com/attachments/435392929847312392/465627498718167041/unknown.png
and 1 minute after
https://cdn.discordapp.com/attachments/435392929847312392/465631339908169729/unknown.png

**Comment by mxnmnm** [comment]
For me it also fills up with stuff from biomes o plenty, botania, thaumcraft, and natura

**Comment by LemADEC** [comment]
What's the minimum set of mods that reproduce the issue?

**Comment by mxnmnm** [comment]
I tried it with biomes o plenty and valkyrien warfare alone and my inventory filled up with biomes o plenty stuff.  It seems like you just need the mod that puts stuff in your inventory and this mod.

**Comment by mxnmnm** [comment]
Ok I after testing with the version on curse forge and the version on jenkins (build 329) that version seems to have fixed it

**Comment by Rubyjunk** [comment]
This should be fixed with the latest curseforge 0.9 final and some builds before that.
