### ISSUE TITLE
RENDER BUG

### ISSUE THREAD

**Issue by 19PHOBOSS98** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#178]
![image](https://user-images.githubusercontent.com/37253663/42451837-3be97a38-833d-11e8-95aa-daa0e482492b.png)

I have no other mods installed...
its running on forge 14.21.1.2443...
help

**Comment by gnomed-by-steve** [comment]
what did you do bryan? WHAT DID YOU DO???




Sorry that was a joke

**Comment by Best108** [comment]
Old issue, closed.
