### ISSUE TITLE
What can I do about runaway airships? 

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#179]
I made a few airships and attached those etherium blocks to them. They promptly flew away and are now tens of thousands of blocks high.

This is doing some damage to my TPS. Is there any way I can remove them? Maybe a kill command?

**Comment by aaronhowser1** [comment]
It would be cool if there was a command to teleport a ship to you for cases like this, and another to freeze the physics for them.

**Comment by Gammaboy45** [comment]
You can put teleporters on your ship. I find that signposts work, and the changelog in the saves say that it works with Simple Teleporters.

If you have a mod like Xaero's minimap, you can set waypoints; however, you cannot set them to a location on the ship without finding the position in which the ship exists in the world. I used the wiring from immersive engineering to get a point, there may be other methods you can use. If you set the position to that point, you can easily teleport there with the waypoint or the /teleport command.

If you do either of these before meddling too much with your ship, you can easily get back onboard your ship remotely in the case that you misplace it or it magically "misplaces" itself.

**Comment by Best108** [comment]
Old issue, closed.

**Comment by TheDeviantCrafter** [comment]
This is more of a server administration issue. Runaway ships cause a lot of lag simply by existing, and admins need a way to delete them.

Players can certainly think ahead and place a teleporter, but most don't in my experience. We need a solution for people who don't think ahead, or aren't familiar with the mod.

**Comment by DeltaNedas** [comment]
use ship kill command or mc kill
