### ISSUE TITLE
its a bit off...

### ISSUE THREAD

**Issue by 19PHOBOSS98** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#180]
this is from the latest build: Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update]
![screen shot 2018-07-10 at 11 54 10 am](https://user-images.githubusercontent.com/37253663/42488903-a5079dda-843a-11e8-9161-411ad1562bb1.jpg)
this is from an earlier build: Valkyrien+Warfare+0.9_pre_3+[HotFix]
![screen shot 2018-07-10 at 12 00 06 pm](https://user-images.githubusercontent.com/37253663/42488955-e1194756-843a-11e8-83e3-17030bcb10b5.jpg)

hope you could fix it :)

**Comment by Best108** [comment]
Old issue, closed.
