### ISSUE TITLE
You can use an RFTools Matter Receiver to teleport to a ship, but you can't use a Matter Transmitter to teleport FROM a ship

### ISSUE THREAD

**Issue by aaronhowser1** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#181]
The fact that Matter Receivers work is actually really surprising, but Matter Transmitters don't work. It could be because they need you to be standing on top of the block, which could be confused because it's technically hundreds of thousands of blocks away.

**Comment by Best108** [comment]
Old issue, closed.
