### ISSUE TITLE
Valkyrien Warfare + Thicc Entities failure to launch game.

### ISSUE THREAD

**Issue by tacticalretard** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#182]
Mod Version: Valkyrien Warfare 0.9_prerelease_5 [Optimization Update]
Forge Version: 1.12.2-14.23.4.2705

Whenever I try to load the Valkyrien Warfare mod alongside the Thicc Entities mod, the game never loads up. I click play on the launcher, and monitor it with task manager. The game uses practically no resources on my computer at all, and never starts loading up. I checked my logs, and it kept mentioning some kind of failure to launch.

I have posted my latest.log on pastebin: https://pastebin.com/y00giPG8

Would this be possible to fix? I'm not sure if it's a problem caused by me or by one of the mods.

**Comment by Best108** [comment]
Old issue, closed.
