### ISSUE TITLE
Render Bug

### ISSUE THREAD

**Issue by Jonarlin** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#184]
Mostly transparent blocks become see-through, they show the sky color insted of their own texture. Have encountered with solid blocks as well not nearly as frequent. 
Forge Version: 14.23.4.2739
VW Version: Valkyrien Warfare 0.9_prerelease_5 [Optimization Update]
![2018-07-28_13 11 03](https://user-images.githubusercontent.com/22119427/43355607-e58ef246-9267-11e8-90c7-1fdbf9724e43.png)
![2018-07-28_13 11 10](https://user-images.githubusercontent.com/22119427/43355608-e5abfca6-9267-11e8-8352-7db5b91ee534.png)
![2018-07-28_13 11 26](https://user-images.githubusercontent.com/22119427/43355609-e5c8ad38-9267-11e8-8a1a-a1b63f0f67fa.png)

**Comment by LemADEC** [comment]
This looks like a GLState bleed. Please specify which other mods are presents.

**Comment by Jonarlin** [comment]
https://modlister.com/user/Jonarlin

**Comment by LemADEC** [comment]
ok, that's a lot of mods. Try to reduce it to a minimum allowing to reproduce the issue.
Start by removing all the overlay ones like The One Probe, Though as nails, Albedo, Wizardry and their related library/extensions.

**Comment by Jonarlin** [comment]
Ok, recreated the issue with only Albedo, The One Probe, Tough As Nails and Wizardry, it's Albedo. Thanks for your help.

**Comment by Best108** [comment]
Old issue, closed.
