### ISSUE TITLE
Rendering issue with Optifine Shaders

### ISSUE THREAD

**Issue by misternebula** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#185]
![image](https://user-images.githubusercontent.com/41904486/43395913-b722ff2e-93f7-11e8-907f-8245b5138a84.png)
I am using Optifine HD E1 Ultra with KUDA Shaders v6.5.56. This only affects the ship helm, the ship telegraph and all the engines.

**Comment by LemADEC** [comment]
Report it to Optifine.

**Comment by gnomed-by-steve** [comment]
This is beautiful, I hope we will have an option to toggle it later when it gets fixed! 😆

**Comment by Best108** [comment]
Old issue, closed. I think I've fixed this already.
