### ISSUE TITLE
Quark Chests

### ISSUE THREAD

**Issue by Jonarlin** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#186]
Quark's chests (Spruce Chest, Birch Chest etc..) appear transparent when placed on a ship.

**Comment by LemADEC** [comment]
Any other mods in your modpack?

**Comment by Jonarlin** [comment]
Tested with only Quark, VW and JEI and still happened

**Comment by Best108** [comment]
Old issue, closed. Hopefully this is fixed in the latest jenkins version.
