### ISSUE TITLE
Weird LittleTiles Door behavior

### ISSUE THREAD

**Issue by CreativeMD** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#187]
Hey there,

recently somebody reported me an issue between our mods (https://github.com/CreativeMD/LittleTiles/issues/112).

https://www.youtube.com/watch?v=fKdVk2Kjx9Y

Do you have an idea what is causing it?

**Comment by xunto** [comment]
Looks like they just ignore most of the issues.

**Comment by Best108** [comment]
Old issue, closed.
