### ISSUE TITLE
Ghost flight

### ISSUE THREAD

**Issue by mxnmnm** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#188]
Not sure if this has been reported it before but I'll report it just in case someone hasn't

If you are a decent distance away from the piloting seat it can let you control the ship without putting you in the ship.  If you need a vid or something let me know.

forge-14.23.4.2749
valkyrien warfare-0.9_prerelease_5

**Comment by Best108** [comment]
Old issue, closed. This is a feature not a bug (unironically).
