### ISSUE TITLE
[Rendering] - Particles from Astral Sorcery and Charcoal pit not rendering

### ISSUE THREAD

**Issue by BasieBrinkie** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#193]
Hello,

If i include valkyrien warfare together with either Astral Sorcery or Charcoal pit some particles stop working. the onces i've found are the flares from astrals illumination wand only emits light but stopped rendering its particles. Same goes for charcoal pit. If you light the log piles you can no longer see the smoke it usually generates through blocks
I reproduced this by just throwing valkyrien, astral and charcoal pit together with forge 14.23.4.2760. You don't need to make a ship to replicate this. So this effect happens independently of the ships custom rendering. There might be more particles bugged but couldn't find them yet.

Anyways thanks for reading and creating this mod,
BasieBrinkie

**Comment by BasieBrinkie** [comment]
Ok did some more testing and found out it mostly affects smoke particles. Other particles from the mods work like the containment chalice from AS. This picture also show that breaking blocks and redstone ore functions normally. Torched are bugged and the vanilla furnace too.
![2018-09-17_19 54 56](https://user-images.githubusercontent.com/20798788/45640898-30c69380-bab4-11e8-8588-caf6ee7e6d44.png)

This one is loaded with only Astral Sorcery and charcoal pit and everythings works like expected.
![2018-09-17_19 56 09](https://user-images.githubusercontent.com/20798788/45640866-1d1b2d00-bab4-11e8-978d-ce518e3e9a3f.png)

also tested more items but couldn't find more.

**Comment by BasieBrinkie** [comment]
Ok did some more testing and found out:
If you change this setting in the config
`B:"Enable particle spawns on Ships"=true`
To
`B:"Enable particle spawns on Ships"=false`
Particles start to work again in the world but also does what you expect from this setting. Turning off all the particles on the ship. I feel i'am better off turn particles off on my ships and having particles in my world than the other way around. Preferred to have both though.

**Comment by Best108** [comment]
Old issue, closed. Fixed in the latest jenkins builds.
