### ISSUE TITLE
Compat issue: VW + Embers Rekindled; Ember power particles do not move

### ISSUE THREAD

**Issue by jonqrandom** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#194]
Embers sends its power via particles, which are sent from emitters to receptors. When Embers and VW are installed together (no other mods, latest versions of each, forge-14.23.4.2760), Ember particles just sit in the emitter until their TTL expires.  
  
The first screenshot demonstrates what should happen, the second illustrates this issue;

![2018-09-21_20 30 52](https://user-images.githubusercontent.com/5947255/45902551-50243000-bdd6-11e8-9102-311118901b97.png)
![2018-09-21_20 18 42](https://user-images.githubusercontent.com/5947255/45902552-50bcc680-bdd6-11e8-9fe4-3308c4fc1a4f.png)

When I searched to see if this had been reported already, I noticed it seems very similar to #171 , with regards to "stuck" particles. not sure if that's helpful?

Also, I'm afraid no messages appeared in the console while the particles stayed still.

**Comment by BasieBrinkie** [comment]
Have you tried my solution in my last post? #193
Dont know if it helps but trying never hurts right?

**Comment by jonqrandom** [comment]
ah, yes, i'm afraid i did, but it doesn't help in this case. thanks anyway! :)

**Comment by Best108** [comment]
Found and fixed in ac19c10bd802bbae8803389c5f9edfed8fc920b8
