### ISSUE TITLE
Thaumcraft Incompatibility

### ISSUE THREAD

**Issue by Keyedrin** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#195]
When Valkyrien Warfare and Thaumcraft are installed alongside each other, the Flux Rifts from Thaumcraft have a few issues. They will visually glitch and appear to teleport around even though the actual rift entity is sitting in one spot, and when collapsing a rift, an item called Void Seeds are supposed to spawn, however they do not appear. After removing Valkyrien Warfare and testing this again, the visual glitches stopped, and the seeds appeared after the rift was collapsed.

If this is not a problem on this mod's end, I will post an issue to Azanor's GitHub as well.

**Comment by gnomed-by-steve** [comment]
sounds like a physics bug. Quote: "item called Void Seeds are supposed to spawn" If they are supposed to spawn like a normal item, the could be physics related. But I'm not an expert.

**Comment by Best108** [comment]
Old issue, closed. I think I fixed this when I fixed the embers particle bug.
