### ISSUE TITLE
Botania's Luminizer does not work when Valkyrien Warfare is installed

### ISSUE THREAD

**Issue by Alan19** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#197]
When I right click a luminizer when this mod is installed, I 'enter' the Luminizer but I do not get moved. Removing this mod allows it to transport my character. 

Forge version: 14.23.4.2765
Botania version: r1.10-354
Valkyrien Warfare version: 0.9_prerelease_5 [Optimization Update]

I've also opened an issue in Botania's GitHub
https://github.com/Vazkii/Botania/issues/2760

**Comment by Best108** [comment]
Old issue, closed.
