### ISSUE TITLE
Game freezes when arrow is shot through ship into water

### ISSUE THREAD

**Issue by Jorgee9001** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#198]
If you take a physics-imbued ship, pilot it just above the water, and then shoot an arrow at it, the arrow will pass through the ship (known issue). However, if the arrow goes through the water the game suddenly locks up and freezes, forcing you to manually close the program. The game will not freeze if the arrow does not go into the water.

To replicate: Make a ship, have it hover around water level, and then shoot an arrow into the bottom.

Forge version: 14.23.5.2770
Minecraft Version 1.12.2
Valkyrien Warfare version: 0.9_prerelease_5 [Optimization Update]

**Comment by Sunspot0411** [comment]
seems this problem exist only with bows, because when i use ic2 mining laser to do the same thing, the game won't freeze and everything works as it suppose to be(of course laser projectile will pass through the ship).

**Comment by Best108** [comment]
Old issue, closed. Fixed in the latest jenkins version.
