### ISSUE TITLE
Crash on second startup during world generation

### ISSUE THREAD

**Issue by gnomed-by-steve** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#200]
I've isolated the mod, used separate versions of both the mod and forge, and cleared the config file.
Clearing the config seems to work, but I don't want to clear my config folder everytime I want to start a new game with the mod installed.

Anyone have a solution or also experiencing the problem?
Oh, and here's a crash report:
**---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (ValkyrienWarfare-Jenkins-341.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 10/25/18 10:00 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.World.func_175725_q(World.java:4685)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:475)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 593969584 bytes (566 MB) / 1254621184 bytes (1196 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID               | Version      | Source                           | Signature                                |
	|:------- |:---------------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft        | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAA | mcp              | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAA | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2772.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge            | 14.23.5.2772 | forge-1.12.2-14.23.5.2772.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | valkyrienwarfare | 0.9_alpha    | ValkyrienWarfare-Jenkins-341.jar | None                                     |

	Loaded coremods (and transformers): 
MixinLoaderForge (ValkyrienWarfare-Jenkins-341.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'**

**Comment by Best108** [comment]
Old issue, closed.
