### ISSUE TITLE
Enabling accurate rain on ships causes crash during world load

### ISSUE THREAD

**Issue by R4inbrew** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#202]
Logs below:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update] (1).jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 11/14/18 6:39 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.World.func_175725_q(World.java:4186)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:435)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_175725_q(World.java:4186)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:435)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: Flytest nibba
	All players: 1 total; [EntityPlayerMP['Rainbrew'/329, l='Flytest nibba', x=68.59, y=101.00, z=174.48]]
	Chunk stats: ServerChunkCache: 636 Drop: 0
	Level seed: -4917984833993254337
	Level generator: ID 03 - amplified, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (61,64,190), Chunk: (at 13,4,14 in 3,11; contains blocks 48,0,176 to 63,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12968 game time, 12968 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 125394 (now: false), thunder time: 60462 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 241583008 bytes (230 MB) / 738197504 bytes (704 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID               | Version          | Source                                                           | Signature                                |
	|:--------- |:---------------- |:---------------- |:---------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft        | 1.12.2           | minecraft.jar                                                    | None                                     |
	| UCHIJAAAA | mcp              | 9.42             | minecraft.jar                                                    | None                                     |
	| UCHIJAAAA | FML              | 8.0.99.99        | forge-1.12.2-14.23.5.2768.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge            | 14.23.5.2768     | forge-1.12.2-14.23.5.2768.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | valkyrienwarfare | 0.9_prerelease_5 | Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update] (1).jar | 8f639e7b2d1117d8f2c5d545e2231f0a0519f0ce |

	Loaded coremods (and transformers): 
MixinLoaderForge (Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update] (1).jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Rainbrew'/329, l='Flytest nibba', x=68.59, y=101.00, z=174.48]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by gnomed-by-steve** [comment]
jesus thank you lord and savior theres a fix for my problem

**Comment by Best108** [comment]
Old issue, closed.
