### ISSUE TITLE
Constant rendering bug

### ISSUE THREAD

**Issue by Gammaboy45** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#203]
Usually, this occurs with a ship that is moving. My screen will go completely solid color- a very light blue. The only way to fix it is to break a block (if I can find one). It persists even over the pause menu. I am playing with a fair number of mods (no optifine). If I find what might be causing the issue, I'll report back here.

**Comment by Gammaboy45** [comment]
It occurs only when I'm in the Misty World, so I can only assume that's the problem. I'll post this issue on MistyWorld's thread, but I don't know what much can be done on either end

**Comment by Best108** [comment]
Old issue, closed.
