### ISSUE TITLE
Ship Stabilization

### ISSUE THREAD

**Issue by Gammaboy45** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#204]
This may be an issue with the ether compressors, or possibly just a problem with compressors placed on different planes than each other. I find that some of my bigger ships tend to bounce up and down violently with only the compressors acting upon them. It will shoot up to the height it is set to, and then it will fail and fall back down to the ground and repeat. No idea what it is. Perhaps its the strength of the compressors or the weight of the ship itself, but it's pretty irritating to keep the ship controlled

**Comment by Best108** [comment]
Old issue, closed. This is fixed in the latest jenkins builds.
