### ISSUE TITLE
ender I/O incompatability

### ISSUE THREAD

**Issue by spiderQuentin** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#206]
many ender I/O menus don't open when used on airships. The only exception that i know of being capacitor banks, vaccum chests and travel anchors (and travel anchors don't work on airships)

**Comment by Best108** [comment]
Old issue, closed. I can't do too much about this, except for maybe adding an api function to allow other mods to get the true distance from the player to the tile entity.
