### ISSUE TITLE
Latest compilable version (v0.9_alpha-full) crashes with OptiFine 1.12.2 E2 installed.

### ISSUE THREAD

**Issue by steampunko** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#208]
[latest.log](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/2646649/latest.log)

Using forge 1.12.2-14.23.5.2795

**Comment by LemADEC** [comment]
Optifine is incompatible with recent changes in Forge, already reported to Optifine issue tracker.

**Comment by steampunko** [comment]
Alright
