### ISSUE TITLE
Attempting to compile the latest dev version results in a failed build

### ISSUE THREAD

**Issue by steampunko** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#209]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve valkyrienwarfare:api:1.0.
  Required by:
      valkyrienwarfare:Valkyrien-Warfare-Revamped:1.12.2-0.9a
   > Could not resolve valkyrienwarfare:api:1.0.
      > Could not get resource 'https://maven.daporkchop.net/valkyrienwarfare/api/1.0/api-1.0.pom'.
         > Could not GET 'https://maven.daporkchop.net/valkyrienwarfare/api/1.0/api-1.0.pom'. Received status code 524 from server: Origin Time-out
   > Could not resolve valkyrienwarfare:api:1.0.
      > Could not get resource 'https://maven.daporkchop.net/valkyrienwarfare/api/1.0/api-1.0.pom'.
         > Could not GET 'https://maven.daporkchop.net/valkyrienwarfare/api/1.0/api-1.0.pom'. Received status code 524 from server: Origin Time-out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
:compileJava

BUILD FAILED

Total time: 6 mins 51.142 secs
Could not GET 'https://maven.daporkchop.net/valkyrienwarfare/api/1.0/api-1.0.pom'. Received status code 524 from server: Origin Time-out
Enable Gradle 'offline mode' and sync project

**Comment by Best108** [comment]
Old issue, closed.
