### ISSUE TITLE
CustomNPCs Vanishing

### ISSUE THREAD

**Issue by bamcat** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#213]
After a few seconds of CustomNPCs being on a ship, they vanish and do not come back.

I use 1.12.2

CustomNPCs made by  noppes  (https://minecraft.curseforge.com/projects/custom-npcs/files)
I don't know if this happens to anyone else.

It also takes less time until it vanishes when the ship is moving.

**Comment by bamcat** [comment]
i found out how to fix it

turn off  "go back to start" in custom npcs, close this issue

**Comment by Best108** [comment]
Old issue, closed.
