### ISSUE TITLE
rain, collision & water bug

### ISSUE THREAD

**Issue by pitrouA** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#215]

**Comment by pitrouA** [comment]
Hello everybody.

I'm a french student using your mod ( my English is not marvelous ). I like very much your work.

I would like to declare many bugs I've found

1 ) It rain IN ships. The rain cross the ceiling !

2) I can't climb ladders in ships

3 ) In ships, the water is not really water, we can't swim in.

4 ) 2 ships does not collide between them. A ship is a "ghost" without another ship. But the player is killed.

5 ) When i sit in pilot's seat, i can' t leave it pressing w. I must quit the game and restart to quit or using \tp command

I hope you'll fix them and good luck to you, it's really an incredible work !

**Comment by feherneoh** [comment]
5:
Why would it let you leave by moving? The whole point of mounting stuff is exactly to be kept in place
You can leave the pilot chair/seat, just press shift, like you would to unmount from any animal/boat/cart

**Comment by pitrouA** [comment]
The first time it works, but the second it failed. I don't understand this behavior... The passenger seat don't seem to have the same problem.

**Comment by Sunspot0411** [comment]
if you want to walk on a ship while it's moving, you should use engines to propel your ship. you just need levers to active/de-active them

**Comment by Rubyjunk** [comment]
Besides the rain, these issues are known and can be found in the github at various places. Thanks for your report, but I'm going to close this since I'm cleaning up old issues right now.

Thanks again!
