### ISSUE TITLE
Missing null check

### ISSUE THREAD

**Issue by Rubyjunk** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#217]
https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/8778e9d45f16c1f60e8149ab6cbdbabbdebc1278/src/main/java/valkyrienwarfare/api/block/ethercompressor/TileEntityEtherCompressor.java#L104

`PhysicsObject physObj = ValkyrienWarfareMod.physicsManager.getObjectManagingPos(world, pos).wrapping;`

This needs to have a null check, or that method needs to never return null

**Comment by Best108** [comment]
That code has since been deleted in the control-system-revamp branch.
