### ISSUE TITLE
Ship drifting and propellers are facing the wrong way

### ISSUE THREAD

**Issue by Nulwraith** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#222]
Without any engines turned on, the ship is drifting slowly. Plus the propellers only work when facing backwards.

please see gif as proof
https://gfycat.com/AcclaimedCalculatingDromedary

**Comment by Best108** [comment]
The rendering bug has been fixed. As for the drifting you didn't connect the gearboxes correctly relative to the chadburn.
