### ISSUE TITLE
[Long-Term Suggestion] Rewrite ship storage system to be like the old MetaWorlds mod

### ISSUE THREAD

**Issue by seancrain** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#224]
Back in 2014, there was a mod called MetaWorlds, and it provided ships that supported collision detection, essentially doing the same things as Valkyrien Warfare does now.

However, one key difference is that MetaWorlds stored each ship in its own subworld instead of beyond a certain distance in the main world. Perhaps in the future, the code could be rewritten to utilize this instead of the current system.

**Comment by DaMatrix** [comment]
the fact that the ships are stored in the same world is the only reason why this mod has so much better compatibility with other mods. this is a nofix, as doing that would effectively invalidate that major advantage vw has over other similar mods.

**Comment by seancrain** [comment]
Understandable
