### ISSUE TITLE
Coremod Incompatibility with Numerous Mods

### ISSUE THREAD

**Issue by Nimbleguy** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#226]
The latest Jenkins (#413) and before (other tested versions include #410 and #400) encounter issues with several mods. When Valkyrien Warfare is installed, entities from Astral Sorcery (eg shooting star), Embers (eg golem projectile), and Roots crash the client, Embers transmission doesn't work, and multiple tools from the listed mods are dysfunctional.

The issue currently seems to be a problem with the mixin coremod modifying positioning code.

Currently we have narrowed it down to VW through the following test:

1. Control w/ or w/o VW
2. Install only Embers and the Aetherworks addon
3. Give self the Pickaxe of the Boundless Sky
4. Dig down a distance into stone
5. Right click on wall with pickaxe

When VW is installed, an exception occurs. This could be used to help debug and test if fixes work.

Some logs:
Exception with pickaxe https://paste.dimdev.org/misosiwesu.mccrash
Crash with Embers projectile https://paste.dimdev.org/omevixocid.mccrash

**Comment by Nimbleguy** [comment]
Note that this is reproducible with only VW and the affected mods, VanillaFix in the first report is only used for ease of exception collection and upload.

**Comment by Best108** [comment]
Fixed!
