### ISSUE TITLE
Game crashes when starting.

### ISSUE THREAD

**Issue by groosen** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#228]
I'm trying to add this to a modpack, and while I know it can be risky business, I just want to know what's causing it so I can m a y b e fix it.
this is what my log says:
[latest.log](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/3199627/latest.log)

**Comment by groosen** [comment]
From what it says, it might have something to do with mixin, but I have no idea what that even means.

**Comment by Best108** [comment]
I don't think VW is causing this crash. Does this still occur when you've removed VW?

**Comment by groosen** [comment]
No, and when I tried with a different modpack, it worked. But that modpack had a older version of forge (14.23.4.2749 to be somewhat specific), and when I updated it's forge I got the error. So I'm thinking something in a forge update has messed up the mod?

**Comment by Best108** [comment]
Can you test this again using the latest jenkins build?

**Comment by groosen** [comment]
Yeah, seems like it's working now.
