### ISSUE TITLE
Sleeping on bed while on ship crashes the game

### ISSUE THREAD

**Issue by Best108** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#23]
Also getting pushed by pistons does something similar

**Comment by DaMatrix** [comment]
I'm getting started with the whole EntityDraggable thing, as you said that should fix it.

**Comment by BigBastard** [comment]
*Update: Sleeping on beds no longer crashes the game, but isn't fully functional yet. Will close once I've implemented it 100%

**Comment by Best108** [comment]
Removing old issue.
