### ISSUE TITLE
Error while starting sponge server

### ISSUE THREAD

**Issue by DotIN13** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#236]
Hey guys!

I'm setting up a sponge server with Sponge 7.1.6 & Forge 2825. But I keep getting this output and my server would not start. Valkyrien Warfare is the only mod installed on this server in this case.

Any help would be appreciated!

`[main/ERROR] [mixin]: Mixin config mixins.valkyrienwarfare.json does not specify "minVersion" property`

Full log:
https://pastebin.com/8vhzWcAG

**Comment by Best108** [comment]
I've removed the conflicting method so this shouldn't happen anymore. I've confirmed Aether II works with version 450.
