### ISSUE TITLE
Client crash when entering other dimensions or getting near some chunks like spawn.

### ISSUE THREAD

**Issue by ryukra** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#237]
https://paste.dimdev.org/navefufuha.mccrash

**Comment by ryukra** [comment]
https://paste.dimdev.org/iheqiceyob.mccrash

**Comment by ryukra** [comment]
I think the problem might be the mod v10verlap

**Comment by ryukra** [comment]
https://paste.dimdev.org/udezuyosil.mccrash

**Comment by Best108** [comment]
Does this issue still occur in the latest jenkins build?

**Comment by ryukra** [comment]
Still occurs.. https://paste.dimdev.org/jikebacoza.mccrash

**Comment by Best108** [comment]
This bug should now be impossible.

**Comment by ryukra** [comment]
Thx for fixing.. now the ships dissappear until reconnecting, but thats better than players crashing. :)
