### ISSUE TITLE
Сrash  if ship when  assembling    have Mekanism

### ISSUE THREAD

**Issue by zayats1** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#243]
https://paste.dimdev.org/huwexonewi.mccrash

**Comment by Best108** [comment]
I think I've fixed it in build 448. Can you verify its fixed?

**Comment by zayats1** [comment]
50/50
 Cables from Mekanism are transparent. Ic2 Cales i will test tomorrow

**Comment by zayats1** [comment]
Crashes this tipe not found ^-^ ))

**Comment by Best108** [comment]
Nice! Another bug fixed.
