### ISSUE TITLE
Useless code in vw! Rework on delete it.(Priority set yourself)

### ISSUE THREAD

**Issue by zayats1** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#259]
https://imgur.com/a/EZUu9Zw

**Comment by DaMatrix** [comment]
We already know that the codebase is already a horrible mess of unused and duplicated code.

**Comment by zayats1** [comment]
ok

**Comment by Rubyjunk** [comment]
Your link is dead and we're already doing a ton of refactoring and rewriting. Thanks for looking through our code and if you have any suggestions feel free to PR any changes!
