### ISSUE TITLE
VW not playing nice with spongeforge, crashing server. 

### ISSUE THREAD

**Issue by DeadlyForest** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#261]
EDIT: Delete this, I was unaware I was using a version from 13 months ago. (From curseforge)

https://pastebin.com/catZPzsb 

Worked fine before I put in spongeforge, then the server crashed. Then I took VW out and the server worked fine without it. So spongeforge and VW cannot coexist at the moment apparently. The pastebin is the console output from the start of the server until the crash, since the server didn't produce a proper crashlog.

**Comment by Rubyjunk** [comment]
You can mark as closed 😄

**Comment by Best108** [comment]
Easiest close of my life.
