### ISSUE TITLE
New controll  system  for chair( Feature request)

### ISSUE THREAD

**Issue by zayats1** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#262]
https://imgur.com/HeEFE5c
https://imgur.com/mnXpO14
 Limits:
 1-2 pilot chair
4-5 engines small
2 etherum(Valkyrien) compressors
1-2  levers specials
or 1 etherum  engine and vertical  propeller .
  Make    physics like plane planes (low priority).
 Enable pilot chair option should be  configurable.

Good codding day)!

**Comment by Rubyjunk** [comment]
Game controls are getting reworked into different mods for different control systems. Thanks for your contribution, it's really appreciated. If you want to provide more input for the future systems, please wait a little while for us to update them and we'd love to hear your feedback. I'm definitely going to keep this in mind, but closing this issue to keep the issues clean. Thanks again!
