### ISSUE TITLE
getting pushed out of ship in survival

### ISSUE THREAD

**Issue by ThsHaunted124** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#268]
The issue is that in creative everythig works 100% well but when i switch to survival in my flying ship i tend to get pushed out of my ship and fall to my death. This happens when i touch a wall in my ship or when i walk around too much. 

the moment this happens i clip trough my ship and the ship flies away while im still in the same spot in mid air, then after a couple seconds of my screen vibrating i fall to the ground. 

i am using this mod in a small modpack. idk if that is the reason its happening but all none of the mods seem to be interfering with the performence of this mod.

**Comment by Rubyjunk** [comment]
This will get fixed with the implementation of the subspace system. For now you can use passenger chairs while the ship is moving at significant speed.

**Comment by zayats1** [comment]
Mod is too unstable for survival.Recipes can  be create  with Crafttweaker WurmTweaks or IGCM

**Comment by Sunspot0411** [comment]
This issue is already fixed for the newest version, please tell us which vw version are you using?

**Comment by ThsHaunted124** [comment]
Im using ValkyrienWarfare-1.12.2-0.9.5-universal.jar<https://www.curseforge.com/minecraft/mc-mods/valkyrien-warfare/files/2570337>. Its currently the newest one on https://www.curseforge.com/minecraft/mc-mods/valkyrien-warfare/files

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Sunspot0411 <notifications@github.com>
Verzonden: Thursday, July 25, 2019 6:49:11 PM
Aan: ValkyrienWarfare/Valkyrien-Warfare-Revamped <Valkyrien-Warfare-Revamped@noreply.github.com>
CC: ThsHaunted124 <wwbij@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ValkyrienWarfare/Valkyrien-Warfare-Revamped] getting pushed out of ship in survival (#268)


This issue is already fixed for the newest version, please tell us which vw version are you using?

**Comment by Sunspot0411** [comment]
As i expected, the one on curseforge is a very very old version, go on and try the real newest version on #updates of discord community.

**Comment by ThsHaunted124** [comment]
Thanks that solves a lot. So far i thought that curseforge was the main place where all the newest mods are put on. Next time i will try to dig a bit deeper before reporting a problem

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Sunspot0411 <notifications@github.com>
Verzonden: Friday, July 26, 2019 9:33:54 AM
Aan: ValkyrienWarfare/Valkyrien-Warfare-Revamped <Valkyrien-Warfare-Revamped@noreply.github.com>
CC: ThsHaunted124 <wwbij@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ValkyrienWarfare/Valkyrien-Warfare-Revamped] getting pushed out of ship in survival (#268)


As i expected, the one on curseforge is a very very old version, go on and try the real newest version on #updates of discord community.

**Comment by Rubyjunk** [comment]
My bad, sorry guys for not investigating further. It's just that this system is being overhauled anyways.
