### ISSUE TITLE
Configurable ship block blacklist

### ISSUE THREAD

**Issue by gt22** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#272]
Currently, blacklist for ship's blocks is set directly in ShipSpawnDetector, and is umodifieble (for compiled mod). I think it would be better to move it to config file, so players can add/remove some blocks from it.

**Comment by Rubyjunk** [comment]
Will be added with #265

**Comment by Rubyjunk** [comment]
Hi, this has been implemented. You can download the latest builds for this feature branch here: https://circleci.com/gh/ValkyrienWarfare/Valkyrien-Warfare-Revamped/tree/feature%2Fconfigurable-blacklist

It will be merged into master shortly and will show up in the latest release after that. Thanks for your suggestion!
