### ISSUE TITLE
Crash  when generating world

### ISSUE THREAD

**Issue by zayats1** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#278]
https://pastebin.com/tKTu3V4z

**Comment by Best108** [comment]
Perhaps I should disable ships in certain worlds, like those of little tiles.

**Comment by Best108** [comment]
Try again with jenkins 461.

**Comment by zayats1** [comment]
ok
Thank you

**Comment by zayats1** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre151_mc1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-161-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  WarpDriveCore (WarpDrive-1.12.2-1.5.5.jar)
  SoundUnpack (OpenSecurity-MC1.12.2-1.0-32.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  MixinLoaderForge (ValkyrienWarfareRevamped-1.12.2-0.9a-full-jenkins-461.jar)
  CreativePatchingLoader (CreativeCore_v1.9.55_mc1.12.2.jar)
  IGCMPatchingLoader (IGCM_v1.2.10_mc1.12.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/29/19 3:38 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at valkyrienwarfare.mod.common.ship_handling.WorldServerShipManager.onWorldUnload(WorldServerShipManager.java:35)
	at net.minecraft.world.WorldServer.handler$beforeWorldUnload$zbe000(WorldServer.java:1944)
	at net.minecraft.world.WorldServer.func_73041_k(WorldServer.java)
	at net.minecraft.world.WorldServerMulti.func_73041_k(WorldServerMulti.java:87)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:256)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2811614680 bytes (2681 MB) / 4819255296 bytes (4596 MB) up to 4819255296 bytes (4596 MB)
	JVM Flags: 5 total; -XX:+UseG1GC -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -Xmx4596M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E4_pre4 79 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version               | Source                                                    | Signature                                |
	|:------ |:-------------------- |:--------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                | minecraft.jar                                             | None                                     |
	| LCHIJA | mcp                  | 9.42                  | minecraft.jar                                             | None                                     |
	| LCHIJA | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2838.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2838          | forge-1.12.2-14.23.5.2838.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore | 1                     | minecraft.jar                                             | None                                     |
	| LCHIJA | creativecoredummy    | 1.0.0                 | minecraft.jar                                             | None                                     |
	| LCHIJA | itemphysic           | 1.4.0                 | minecraft.jar                                             | None                                     |
	| LCHIJA | littletilescore      | 1.0.0                 | minecraft.jar                                             | None                                     |
	| LCHIJA | foamfixcore          | 7.7.4                 | minecraft.jar                                             | None                                     |
	| LCHIJA | opencomputers|core   | 1.7.4.153             | minecraft.jar                                             | None                                     |
	| LCHIJA | WarpDriveCore        | 1.12.2-1.5.5.SNAPSHOT | minecraft.jar                                             | None                                     |
	| LCHIJA | techguns_core        | 1.12.2-1.0            | minecraft.jar                                             | None                                     |
	| LCHIJA | ic2                  | 2.8.1000              | IC2Classic+1.12-1.5.4.4.jar                               | None                                     |
	| LCHIJA | libvulpes            | 0.4.1.-60             | LibVulpes-1.12.2-0.4.1-60-universal.jar                   | None                                     |
	| LCHIJA | advancedrocketry     | 1.6.0.-161            | AdvancedRocketry-1.12.2-1.6.0-161-universal.jar           | None                                     |
	| LCHIJA | architecturecraft    | @VERSION@             | architecturecraft-1.12-3.98.jar                           | None                                     |
	| LCHIJA | backups              | 1.4.5                 | Backups-1.12.2-1.4.5.jar                                  | None                                     |
	| LCHIJA | baubles              | 1.5.2                 | Baubles-1.12-1.5.2.jar                                    | None                                     |
	| LCHIJA | jei                  | 4.15.0.268            | jei_1.12.2-4.15.0.268.jar                                 | None                                     |
	| LCHIJA | reborncore           | 3.14.1.457            | RebornCore-1.12.2-3.14.1.457-universal.jar                | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | techreborn           | 2.23.2.1007           | TechReborn-1.12.2-2.23.2.1007-universal.jar               | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | forestry             | 5.8.2.387             | forestry_1.12.2-5.8.2.387.jar                             | None                                     |
	| LCHIJA | beebetteratbees      | 2.0.3                 | beebetteratbees-1.12.2-2.0.3.jar                          | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | biomesoplenty        | 7.0.1.2439            | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar             | None                                     |
	| LCHIJA | cctweaked            | 1.83.1                | cc-tweaked-1.12.2-1.83.1.jar                              | None                                     |
	| LCHIJA | computercraft        | 1.83.1                | cc-tweaked-1.12.2-1.83.1.jar                              | None                                     |
	| LCHIJA | igcm                 | 1.2.2                 | IGCM_v1.2.10_mc1.12.2.jar                                 | None                                     |
	| LCHIJA | creativecore         | 1.9.9                 | CreativeCore_v1.9.55_mc1.12.2.jar                         | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22     | CTM-MC1.12.2-0.3.3.22.jar                                 | None                                     |
	| LCHIJA | engineersdecor       | 1.0.9                 | engineersdecor-1.12.2-1.0.9.jar                           | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | theoneprobe          | 1.4.28                | theoneprobe-1.12-1.4.28.jar                               | None                                     |
	| LCHIJA | immersiveengineering | 0.12-89               | ImmersiveEngineering-0.12-89.jar                          | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | engineersdoors       | 0.8.0                 | engineers_doors-1.12.2-0.8.0.jar                          | None                                     |
	| LCHIJA | extrautils2          | 1.0                   | extrautils2-1.12-1.9.9.jar                                | None                                     |
	| LCHIJA | foamfix              | 0.10.5-1.12.2         | foamfix-0.10.5-1.12.2.jar                                 | None                                     |
	| LCHIJA | gravestone           | 1.10.2                | gravestone-1.10.2.jar                                     | None                                     |
	| LCHIJA | ic2-classic-spmod    | 0.0.0.0               | IC2Classic+1.12-1.5.4.4.jar                               | None                                     |
	| LCHIJA | gravisuit            | 1.0.6.2               | gravisuit-1.0.6.2.jar                                     | None                                     |
	| LCHIJA | ic2c_extras          | 1.4.3                 | IC2CExtras-1.4.3.jar                                      | None                                     |
	| LCHIJA | immersivepetroleum   | 1.1.9                 | immersivepetroleum-1.12.2-1.1.9.jar                       | None                                     |
	| LCHIJA | immersivetech        | 1.3.10                | immersivetech-1.12-1.3.10.jar                             | None                                     |
	| LCHIJA | littletiles          | 1.5.0                 | LittleTiles_v1.5.0-pre151_mc1.12.2.jar                    | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                              | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                             | None                                     |
	| LCHIJA | matchlockweapons     | 0.6                   | Matchlock+Guns+Mod-1.12.2-4b.jar                          | None                                     |
	| LCHIJA | redstoneflux         | 2.1.0                 | RedstoneFlux-1.12-2.1.0.6-universal.jar                   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | mekanism             | 1.12.2-9.8.0.381      | Mekanism-1.12.2-9.8.0.381.jar                             | None                                     |
	| LCHIJA | mekanismgenerators   | 1.12.2-9.8.0.381      | MekanismGenerators-1.12.2-9.8.0.381.jar                   | None                                     |
	| LCHIJA | mekanismtools        | 1.12.2-9.8.0.381      | MekanismTools-1.12.2-9.8.0.381.jar                        | None                                     |
	| LCHIJA | nuclearcraft         | 2.17b                 | NuclearCraft-2.17b-1.12.2.jar                             | None                                     |
	| LCHIJA | mekores              | 2.0.7                 | mekores-2.0.7.jar                                         | None                                     |
	| LCHIJA | opencomputers        | 1.7.4.153             | OpenComputers-MC1.12.2-1.7.4.153.jar                      | None                                     |
	| LCHIJA | ocdevices            | snapshot_20190121     | ocdevices-snapshot_20190121.jar                           | None                                     |
	| LCHIJA | omlib                | 3.1.3-246             | omlib-1.12.2-3.1.3-246.jar                                | None                                     |
	| LCHIJA | ompd                 | 3.1.0-61              | ompd-1.12.2-3.1.0-61.jar                                  | None                                     |
	| LCHIJA | openmodularturrets   | 3.1.3-355             | openmodularturrets-1.12.2-3.1.3-355.jar                   | None                                     |
	| LCHIJA | openscreens          | 1.0.0                 | openscreens-1.12.2-1.0.0.jar                              | None                                     |
	| LCHIJA | opensecurity         | 1.0-32                | OpenSecurity-MC1.12.2-1.0-32.jar                          | None                                     |
	| LCHIJA | plasmacannons        | 0.1                   | PlasmaCannon-1.2.jar                                      | None                                     |
	| LCHIJA | plasmaengines        | 0.1                   | PlasmaEngine-1.1.jar                                      | None                                     |
	| LCHIJA | plethora-core        | 1.2.2                 | plethora-1.12.2-1.2.2.jar                                 | None                                     |
	| LCHIJA | plethora             | 1.2.2                 | plethora-1.12.2-1.2.2.jar                                 | None                                     |
	| LCHIJA | psf                  | 0.2.0                 | practical-space-fireworks-0.2.0.7.jar                     | None                                     |
	| LCHIJA | refinedstorage       | 1.6.15                | refinedstorage-1.6.15.jar                                 | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | rebornstorage        | 1.0.0                 | RebornStorage-1.12.2-3.3.4.85.jar                         | None                                     |
	| LCHIJA | refinedstorageaddons | 0.4.4                 | refinedstorageaddons-0.4.4.jar                            | None                                     |
	| LCHIJA | sgcraft              | 1.13.2                | SGCraft-2.0.1.jar                                         | None                                     |
	| LCHIJA | techguns             | 2.0.1.2               | techguns-1.12.2-2.0.1.2_1.jar                             | None                                     |
	| LCHIJA | tmel                 | 1.12.2-1.4.0.0        | tmel-1.12.2-1.4.0.0.jar                                   | None                                     |
	| LCHIJA | topaddons            | 1.12.2-1.11.0         | topaddons-1.12.2-1.11.0.jar                               | None                                     |
	| LCHIJA | valkyrienwarfare     | 0.9.2                 | ValkyrienWarfareRevamped-1.12.2-0.9a-full-jenkins-461.jar | b308676914a5e7d99459c1d2fb298744387899a7 |
	| LCHIJA | viesmachines         | 1.0.0 - MC 1.12.2     | viesmachines-1.12.2-1.0.0.jar                             | None                                     |
	| LCHIJA | warpdrive            | 1.12.2-1.5.5.SNAPSHOT | WarpDrive-1.12.2-1.5.5.jar                                | f7be6b40743c6a8205df86c5e57547d578605d8a |
	| LCHIJA | xaerominimap         | 1.17.4                | Xaeros_Minimap_1.17.4_Forge_1.12.jar                      | None                                     |
	| LCHIJA | xaeroworldmap        | 1.4.3                 | XaerosWorldMap_1.4.3_Forge_1.12.jar                       | None                                     |
	| LCHIJA | zwangcraft           | 1.12.2-r3.1           | zwangcraft-1.12.2-r3.1.jar                                | None                                     |
	| LCHIJA | matteroverdrive      | 0.7.0.0               | MatterOverdrive-1.12.2-0.7.1.0-universal.jar              | None                                     |
	| LCHIJA | techreborn_compat    | 1.0.0                 | TechReborn-ModCompatibility-1.12.2-1.1.0.49.jar           | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	|        | ic2caddons           | 1.0.2                 | ic2caddons-1.0.2.jar                                      | None                                     |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre151_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-161-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
WarpDriveCore (WarpDrive-1.12.2-1.5.5.jar)
  cr0s.warpdrive.core.ClassTransformer
SoundUnpack (OpenSecurity-MC1.12.2-1.0-32.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MixinLoaderForge (ValkyrienWarfareRevamped-1.12.2-0.9a-full-jenkins-461.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.55_mc1.12.2.jar)
  
IGCMPatchingLoader (IGCM_v1.2.10_mc1.12.2.jar)
  com.creativemd.igcm.core.IGCMTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  mekanism.coremod.KeybindingMigrationHelper
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.14.1.457
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E4_pre4
	OptiFine Build: 20190410-123819
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.98
	OpenGlRenderer: GeForce 940MX/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by zayats1** [comment]
Hastebin  and pastebin good but i tired with latest log. It's longer than norma.I send only crashreport.
