### ISSUE TITLE
Network Control Relay on top fencepost

### ISSUE THREAD

**Issue by pkej** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#287]
I love the aesthetics of having the network control relay on a higher place and run the wires like rigging on a ship. Unfortunately, it's not [possible to place it on top of a post](https://pbs.twimg.com/media/EBiouOIWsAIM0fu?format=png&name=small), while full blocks can, as well as torches.

So I have to use a block [giving me this sad state](https://pbs.twimg.com/media/EBipaOpXsAAoJw0?format=png&name=small) :(

**Comment by Rubyjunk** [comment]
Interesting. Will look into it.

**Comment by Rubyjunk** [comment]
We've taken your valuable feedback and added the relevant features to the mod. As of now, these additions have been added to a feature branch and are pending addition to the main Valkyrien Warfare mod. While you are waiting for this to be added to the main mod, you may explore the feature branch using the instructions below.

With <3,
Valkyrien Warfare Team

---

This was added on the branch: `feature/placeable-network-control`

---

**You may obtain the bleeding-edge build of Valkyrien Warfare feature branches on the CircleCI page**

1. Navigate to this URL: https://circleci.com/gh/ValkyrienWarfare/Valkyrien-Warfare-Revamped
2. Click on the latest build prefixed with the branch this was added on
3. Click on artifacts
4. Download the JAR file of the mod
