### ISSUE TITLE
Request: bringing back old config for engines

### ISSUE THREAD

**Issue by nsnl1229** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#288]
Just as the title says, I think it would be nice to have the old config option for controlling the power of each engine back. The current system of the engine is great and realistic, but before it becomes perfect I would like stick to the old version of the engines, as they are more reliable and straightforward.

When I tried to use the old engines, I realized that they have ridiculously low power. Therefore, it would be nice to have an option in the config to change the power of each engine, like the one they have in the latest curse forge version. Thank you!

**Comment by Rubyjunk** [comment]
@Best108 opinions?

**Comment by Rubyjunk** [comment]
OK I changed my mind, we might as well add any config option that people want, no reason not to if it's not difficult. Will add into #265.

**Comment by Rubyjunk** [comment]
Added with #293. Download the latest builds of this feature branch while waiting for it to be merged into master here: https://circleci.com/gh/ValkyrienWarfare/Valkyrien-Warfare-Revamped/tree/feature%2Fconfigurable-engine-power
