### ISSUE TITLE
Make Lift Lever's starting Target Altitude be equal to the Y coordinate of where it was placed in.

### ISSUE THREAD

**Issue by Frazaell** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#296]
It's just that it moves too slowly, and I think this would be a nice QoL addition.

**Comment by Rubyjunk** [comment]
good idea

**Comment by DeltaNedas** [comment]
best idea in years

**Comment by Rubyjunk** [comment]
Hi, and thanks for your report. This issue is being *currently* investigated and is a work in progress. This issue will be updated as progress continues.

*Current time estimate: **<1 week***

**Comment by Best108** [comment]
Very based idea. Here it is friend fb8163d4425468b720290dd8a2781e2d8e4bf4e0

**Comment by Rubyjunk** [comment]
We've taken your valuable feedback and added the relevant features to the mod. As of now, these additions have been merged into the 'master' branch and therefore will be included with the next release of Valkyrien Warfare.

With <3,
Valkyrien Warfare Team

---

**You may obtain the latest, bleeding-edge build of Valkyrien Warfare containing these features and more at the CircleCI page**

1. Navigate to this URL: https://circleci.com/gh/ValkyrienWarfare/Valkyrien-Warfare-Revamped/tree/master
2. Click on the latest build number
3. Click on artifacts
4. Download the JAR file of the mod
