### ISSUE TITLE
Unknown  crash with VW  latest Circle

### ISSUE THREAD

**Issue by zayats1** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#300]
https://paste.dimdev.org/zeyimohoja.mccrash

**Comment by Rubyjunk** [comment]
Hi, and thanks for your report. This issue is being *currently* investigated and is a work in progress. This issue will be updated as progress continues.

*Current time estimate: **<2 day***

**Comment by Rubyjunk** [comment]
We've corrected the relevant bugs in the mod. As of now, these corrections have been added to a feature branch and are pending addition to the main Valkyrien Warfare mod.

I had to do some workaround that disables particles on ships, but at least it works.

With <3,
Valkyrien Warfare Team

---

This was added on the branch: `fix/jar`

---

**You may obtain the bleeding-edge build of Valkyrien Warfare feature branches on the CircleCI page**

1. Navigate to this URL: https://circleci.com/gh/ValkyrienWarfare/Valkyrien-Warfare-Revamped
2. Click on the latest build prefixed with the branch this was added on
3. Click on artifacts
4. Download the JAR file of the mod

**Comment by zayats1** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/Ig0v57T"><a href="//imgur.com/a/Ig0v57T">?</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by zayats1** [comment]
F*ck
imgur

**Comment by zayats1** [comment]
https://imgur.com/gallery/Ig0v57T

**Comment by Rubyjunk** [comment]
Interesting, it looks like the artifacts tab is not available when you're not logged in. Sorry... you can still see them with this link but I will look into a better solution

https://circleci.com/gh/ValkyrienWarfare/Valkyrien-Warfare-Revamped/26#artifacts/containers/0

**Comment by zayats1** [comment]
Thanks!

**Comment by zayats1** [comment]
I logged)
