### ISSUE TITLE
Air ships still ships...

### ISSUE THREAD

**Issue by shoverno2** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#316]
I just wonder, why those ships swims like axe XD
Really, what about some phisics and logic)
Ships should have ability to float.

**Comment by Rubydesic** [comment]
Duplicate of #255, #223 

Also see, https://valkyrienskies.miraheze.org/wiki/RFC:Boats if you want to contribute your ideas. You may discuss any potential ideas using the discussion tab and edit them in using the edit tab.
