### ISSUE TITLE
Crash With Little Tiles Mod

### ISSUE THREAD

**Issue by devalidating** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#36]
Game crashed with little tiles mod as I tried to use to door functionality. Crash log:

[crash-2017-01-23_19.47.58-server.txt](https://github.com/BigBastard/Valkyrien-Warfare-Revamped/files/725594/crash-2017-01-23_19.47.58-server.txt)
[crash-2017-01-23_19.48.07-client.txt](https://github.com/BigBastard/Valkyrien-Warfare-Revamped/files/725593/crash-2017-01-23_19.48.07-client.txt)

**Comment by DaMatrix** [comment]
Client and server both crashed??? wow

**Comment by BigBastard** [comment]
I'm not really sure what to make of this; Little Tiles uses its own separate world to simulate the tiny blocks doing things.

Still looking into it though

**Comment by Best108** [comment]
Old issue, closed.
