### ISSUE TITLE
bug with Tinkers Construct

### ISSUE THREAD

**Issue by EdC94** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#39]
I can't pour anything into a casting table with a cast or a part in it.
However, pouring gold into an empty casting table works.
The casting table is not on a ship.

Tested in a customized Sky Factory 3 instance and in an instance with only those mods:

Mantle-1.10.2-1.1.4
TConstruct-1.10.2-2.6.2
Valkyrien Warfare 0.8.7a
Forge version: forge-12.18.3.2221

**Comment by DaMatrix** [comment]
Can you send us your log? Even if you don't have a crash report the log is still useful.

**Comment by EdC94** [comment]
Here it is:
[latest.log](http://pastebin.com/B9uMQNys)
[fml-client-latest.log](http://pastebin.com/uUAyPRfy)

**Comment by BigBastard** [comment]
Hopefully that fixed things, be sure to reopen the issue if any other problems occur
