### ISSUE TITLE
DecoCraft Bug

### ISSUE THREAD

**Issue by awoychosky123** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#47]
When Generating a ship with DecoCraft items on it. All DecoCraft items turn to "Stuffed Creepers". When placing any DecoCraft items after a ship has been generated will instantly turn the item being place into a "Stuffed Creeper".

**Comment by DaMatrix** [comment]
That is quite literally the strangest bug I've ever heard of. I'll check it out, it sounds like something related to NBT data or sth.

**Comment by Best108** [comment]
Old issue, closed.
