### ISSUE TITLE
Crayfish Furniture Mod Game Freeze

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#48]
Forge 2221
[Crayfish Furniture Mod v4.1.2](https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod)
Valkyrien Warfare v0.8.7b
The game froze after placing a chair on a ship and after I tried to sit in the chair.
There wasn't a crash, a crash report, or anything related to the two mods in the log files.

**Comment by BigBastard** [comment]
Hmmm, I'd probably bet its the same thing that causes crashes when a player uses a bed. I'll look further into this.

**Comment by WenXin20** [comment]
I also noticed that once I had reloaded the game and joined my world again, I was sitting in the chair like it was supposed to.

**Comment by Best108** [comment]
Old issue, closed.
