### ISSUE TITLE
Missing Item Textures

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#50]
I'm not sure if this is known or not, but several items are missing their texture, including the airship stealer and the airship chair.

**Comment by DaMatrix** [comment]
Yeah, we're just too lazy to be bothered to make textures for them. lol

**Comment by BigBastard** [comment]
Lol, to be fair though these items are still very WIP, the current focus is on getting them to work properly. Theres some great stuff coming around the corner though, and these models hopefully wont be an issue for much longer.

**Comment by WenXin20** [comment]
Ok, cool, that's fine. :)

**Comment by Best108** [comment]
Old issue, closed.
