### ISSUE TITLE
Grimpack Mod Fan Block Game Freeze

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#52]
After placing down a fan block, which is meant to push players and other entities, the game freeves or has massive lag. If the fan is managed to be broken, the lag almost immediately dissappears.

**Comment by BigBastard** [comment]
I think this is fixed as of aa66922be985b00dafb40f064327712f528e4556, as there was a similar issue plaguing pistons that also got fixed. I'm closing this for now, but please let me know if this is still an issue.

**Comment by WenXin20** [comment]
I found out that the fans still cause massive lag on ships. I am using v0.8.999 stable on curseforge.
