### ISSUE TITLE
Rails and Minecarts

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#53]
Minecarts can be right-clicked on rails that are attached to a ship, but it won't hook onto the rail.

**Comment by Best108** [comment]
Old issue, closed. It'd be quite challenging to make minecarts really work.

**Comment by DeltaNedas** [comment]
Not an old issue, but yes youre right.
Maybe only try to hook on if its falling towards the rail and not away
proposed solution would also let carts slide away when ship is tilted

**Comment by DeltaNedas** [comment]
![18:33:45](https://user-images.githubusercontent.com/39013340/62152299-2727d200-b2fa-11e9-950d-c9fdb732ce63.png)
tested in jenkins v460
not old at all
