### ISSUE TITLE
Placing a Boat on an Airship

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#54]
I placed a boat on an Airship and then got in the boat and moved the boat around. I was then promptly kicked from my single player world (Not a server) with the message:

> Connection Lost, Flying is not enabled on this server.

**Comment by Divineaspect** [comment]
Is flying enabled on that server?

**Comment by WenXin20** [comment]
It should be, after all, it is my personal single player world and isn't on a server.

**Comment by Divineaspect** [comment]
single player worlds default to no

**Comment by WenXin20** [comment]
The world is a creative world, so is the default still no for creative?

**Comment by BigBastard** [comment]
It's an issue with how the server checks for players cheating. I've already located the code in MC that handles this, it's just a matter of me finally getting around to proper entity integration with Ships.

I'll update you guys when this is fixed.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by Best108** [comment]
Old issue, closed.
