### ISSUE TITLE
Crash w/ Streams Mod &/or Nether Ex Mod

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#57]
Forge 2221
Valkyrien Warfare v0.8.7b
Streams v0.3
Farseek v2.1
Nether Ex v1.1.0b (_Shown as _**nex**_ in the crash log_.)
I got a crash once my world loaded with the Streams Mod.
And, based on the crash log, it looks like the Nether Ex Mod might also be involved.
**Crash Log:**
[crash-2017-02-18_00.59.14-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/784968/crash-2017-02-18_00.59.14-server.txt)

**Comment by WenXin20** [comment]
After starting a game without Nether Ex and only Streams and Valkyrien Warfare, the world loaded fine.
So it looks like the problem is from Nether Ex or both Nether Ex and Streams.

**Comment by BigBastard** [comment]
I am unable to reproduce this bug

**Comment by Best108** [comment]
Old issue, closed.
