### ISSUE TITLE
Crash with spongeforge

### ISSUE THREAD

**Issue by Liiw** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#58]
Hello,

I tried to run Valkyrien Warfare on a SpongeForge server with multiple other mods installed. Unfortunately the server refused to start. I am uploading the server log corresponding to this issue:

[fml-server-latest.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/786213/fml-server-latest.txt)

**Comment by DaMatrix** [comment]
The incompatibility with SpongeForge is already known and rather difficult to fix.

**Comment by BigBastard** [comment]
Update: I have fixed the issue in the log, however it seems Sponge still has 1 or 2 incompatibilities with VW. Will keep investigating, and if I'm fast Sponge should be working by the end of the week.

http://pastebin.com/QkXyFNCy

**Comment by BigBastard** [comment]
Update again, I've fixed another incompatibility that involved spawning entities. The new log http://pastebin.com/f95EPhWU points towards an issue with CallRunner.onUnloadChunk()

I'll update again once Ive fixed that.

**Comment by BigBastard** [comment]
Update #3: SpongeForge no longer crashes with VW, but running both breaks the physics of VW. Will update again once I've fixed that

**Comment by BigBastard** [comment]
I am very proud to announce that as of aa66922be985b00dafb40f064327712f528e4556, Valkyrien Warfare is now fully compatible and functional with SpongeForge. 

I'm closing this issue for now, but feel free to post more if any bugs arise while playing with SpongeForge. Cheers!
