### ISSUE TITLE
Can't open existing world

### ISSUE THREAD

**Issue by Drakoflame** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#59]
not sure if its this mod or another, crash log had lots of names for this mod so I brought it to you http://pastebin.com/8iwYP2mP

**Comment by BigBastard** [comment]
Should be fixed in commit 2c7085aa332da4178eafc0f30f9477ac452afd92

**Comment by BigBastard** [comment]
This has been confirmed as not fixed, still looking into the root again.

**Comment by BigBastard** [comment]
Fixed in 24a2f504c3dc35e596839a8d7a2d14633cb5ad05
