### ISSUE TITLE
Ships behaving strangely and other issues.

### ISSUE THREAD

**Issue by Liiw** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#67]
Hello again!

I was testing build 99 on a fresh SP world and I had a couple of issues with the ships after infusing them with physics. At first I had the issue of ships keeling over and swinging mid-air like pendulums. I soon figured it was just me not configuring the hovercraft controller properly (thrust for stability was set to 0).

Once I had a problem with ships spontaneously rising to high altitudes. I don't know what caused it, but it did not happen in a fresh SP world after that. Perhaps the ship I built was just so ugly that the earth started to actively repel it.

There was also an issue with both of the above combined, at first, the hoverbarge tilted forward at an extreme angle and then refused to level off no matter the amount of thrust I input for stability. Afterwards, I came back to the barge and installed a new Infuser and Hovercraft Controller. After this the ship kept level, but whenever I applied forward momentum with an elite engine, the ship would also start to rise fast. As I cut off the signal to the engine, the ship came back down to Y level 86 as it was set in the HC.

As mentioned in #45 I also had issues with "sliding" off the moving ships in survival mode. I even commandeered a villager's hut, which for it's enclosed space, made for a great shuttle, however I still slid through the walls.

I tried to hijack a lone pirate ship on the seas, but the mod said that this is exceeding the permitted size limit. I tried to change it with /setPhysConstructionLimit, but it wouldn't work. I was given an "unknown command" message.

These issues might have to do with the fact that I have lots of mods installed and things get busy for the PC with chunkloading etc. Once I get the build installed on our SpongeForge server, I will report back of my findings.

**Comment by DaMatrix** [comment]
The ship randomly going up forever is something I've experienced too, relogging (single player) or restarting your server has fixed it every time I've experienced that.  
About that pirate ship: was it touching the ground at all? Also it's `/physSettings <use TAB for options>` now, was changed with the release of 0.8.7 (not sure if the error message says that, though :/)

**Comment by Liiw** [comment]
No, the pirate ship was in water and I double checked, no ground connection. Thank you for clearing up the command confusion. I didn't know that I could use "tab" for options. I will try it. 

I failed to specify that the Infuser told me to use the now obsolete command (/setPhysConstructionLimit).

**Comment by DaMatrix** [comment]
Ah OK, that's easy to fix. @BigBastard probably has some to say about ships going up forever. 
As for the pirate ship, that could do with the algorithm including water when infusing physics on an object. I'll have a look at that too.

**Comment by Liiw** [comment]
Hello again!

I tried build 106 today and was able to assemble a ship I built into water. After a while it started to fly upwards on it's own. I tried to relog into the world (SP) and the game crashed. I am attaching a crash log:

[crash-2017-03-16_16.57.12-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/848123/crash-2017-03-16_16.57.12-server.txt)

**Comment by BigBastard** [comment]
@Liiw I've been trying to track down that error for over a month. Does the crash persist whenever you load the world?

**Comment by Liiw** [comment]
I tried build 109. Created a new SP world, made a ship in the world. After a while it started to fly upwards. I quit the world and relogged into the world. It crashed. I restarted the game and tried to join again, it crashed again. Although, it seemingly rather "froze" than crashed. The crash log appeared in the folder, but nothing indicated, that the game is not responding. Attaching all sorts of stuff in hopes that this will help:



[crash-2017-03-18_05.31.34-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/852129/crash-2017-03-18_05.31.34-server.txt)

[crash-2017-03-18_05.44.07-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/852133/crash-2017-03-18_05.44.07-server.txt)

[fml-client-latest.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/852136/fml-client-latest.txt)

[latest.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/852137/latest.txt)

**Comment by BigBastard** [comment]
I think I found the cause. VW was creating an infinite loop, but the crash itself didn't report as an infinite loop crash because the Chunk Provider was calling Reflection, causing the java.lang.reflect.InvocationTargetException error.

Anyways, as always let me know if this didn't fix it.

https://jenkins.ironhide.de/job/Valkyrien-Warfare-Revamped/111/

**Comment by Liiw** [comment]
That seems to have fixed it! I made a fresh world, built a ship, ship tried to leave the atmosphere, I relogged. The game didn't crash and the ship came down to my preset Y level. Excellent work!

**Comment by BigBastard** [comment]
W00T!

**Comment by Liiw** [comment]
Fair enough, I understand, the other issues require separate threads. 

Anyways, great work on the bugfixing!
