### ISSUE TITLE
Crash when viewing the JEI Furnace Uses for smelting.

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#68]
Valkyrien Warfare v0.8.7-94 Jenkins
Forge 2254
I got this crash when viewing the JEI furnace uses for smelting. I'm not sure if its caused by this mod, but right before the crash happened, I noticed the log produced some errors related to this mod. Unfortunately, the curseforge launcher changed to the new minecraft launcher, so the fml-client-lastest.log didn't form and the lastes.log file deleted everything except the crash log.
[Crash Report](http://pastebin.com/i2tT4yxb)

**Comment by DaMatrix** [comment]
Can you try reproducing this without FoamFix (changes a lot of things), can you please remove Xray (it changes a lot of rendering-related things that could potentially cause issues with VW) and were you able to reproduce it a second time?

**Comment by WenXin20** [comment]
I was able to get it to crash again. The cause isn't from foam fix or Xray, but I still don't know what caused it.  I also noticed that none of the furnace recipes work, nothing will smelt/cook in the furnace. Now I'm not too sure the cause is from your mod.

**Comment by DaMatrix** [comment]
There's nothing there that tells me that it's directly caused by Valkyrien Warfare, more likely its two mods conflicting or an incompatibility with VW. On a side note, could you send your full log as well?

**Comment by WenXin20** [comment]
Here is the log:
[latest.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/852221/latest.txt)

**Comment by WenXin20** [comment]
I figured out the problem, it was an invalid entry in the Crafttweaker scripts.
