### ISSUE TITLE
Move to wrong place when place Thermal Expansion Magmatic Dynamo on ship

### ISSUE THREAD

**Issue by fancl20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#70]
Both Valkyrien-Warfare 0.8.7b and Valkyrien-Warfare 0.8.7-101 (almost) crashed when place Thermal Expansion Magmatic Dynamo on ship
Forge 2185
[CrashReport](http://pastebin.com/sSjaWEAa)

**Comment by Best108** [comment]
Old issue, closed.
