### ISSUE TITLE
JourneyMaps Waypoint markers invisible in the world

### ISSUE THREAD

**Issue by Liiw** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#71]
The waypoints markers from JourneyMaps are not visible in the world. They are there on the map and minimap, but invisible as beacons or labels in the environment. This happened both in the SP world and in the server, when I logged and forgot to remove VW from my mods folder.

**Comment by BigBastard** [comment]
Fixed in latest commit, f852e300542a1ae4582c9f474453b47fcf483a51
![2017-03-17_01 51 11](https://cloud.githubusercontent.com/assets/13895645/24033833/711f2cd2-0ab4-11e7-8434-d32cca48116d.png)
