### ISSUE TITLE
Error when loading up Mod in 1.10.2

### ISSUE THREAD

**Issue by SCABB-9001** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#74]
Hello.
I get this error when loading up the mod on spongeforce 1.10.2 with forge forge-1.10.2-12.18.3.2254

https://hastebin.com/ivolecuruv.md

**Comment by BigBastard** [comment]
Ugh, every time Sponge adds a new Mixin, >:(

I'll get this fixed with haste.

**Comment by BigBastard** [comment]
Fixed as of build 115, sorry about that :/
