### ISSUE TITLE
OpenComputers and ship crash

### ISSUE THREAD

**Issue by djeezuss** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#75]
When I create a ship and then add a computer on it, after a period of time, the game crashes. I tried it with a brand new world, but it crash again when I repeat it.

crash report: [crash-2017-04-03_17.36.35-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/891493/crash-2017-04-03_17.36.35-client.txt)

Also, when I completly destroyed a ship, the entity didn't deleted himself:

![2017-04-03_17 50 32](https://cloud.githubusercontent.com/assets/22917102/24634181/75e6e892-189a-11e7-8892-f2eeaa050388.png)

![2017-04-03_17 50 59](https://cloud.githubusercontent.com/assets/22917102/24634184/7a49759e-189a-11e7-9ef2-3294af1b14a0.png)

![2017-04-03_17 51 47](https://cloud.githubusercontent.com/assets/22917102/24634188/7cff56e6-189a-11e7-884d-f77b1723d40e.png)

As you can see, I destroyed it, but it is still there. On the last screenshot, I did the command "/say @e[r=10]" and it listed the ship and me.

**Comment by BigBastard** [comment]
I'm unable to reproduce this error on version 118

Can you tell me if still occurs?

**Comment by Johncjx** [comment]
It also happened on me without any other mod. 
[crash-2017-04-06_12.43.20-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/901576/crash-2017-04-06_12.43.20-client.txt)
[crash-2017-04-06_12.56.25-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/901578/crash-2017-04-06_12.56.25-server.txt)
[crash-2017-04-06_13.30.45-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/901579/crash-2017-04-06_13.30.45-client.txt)

**Comment by BigBastard** [comment]
Should be fixed as of build 119:

Let me know if the problem persists
