### ISSUE TITLE
Major - Entering World - Crash MC-1.10.2 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#77]
https://gist.github.com/P3rf3ctXZer0/d06135a89fa7ca8c6bb7c286469cb561

**Comment by DaMatrix** [comment]
Can you try to reproduce this with only VW? I can't see any reason why `TileEntity#getWorld` could ever be `null`.

**Comment by BigBastard** [comment]
@DaMatrix I think it might have something to do with the LittleTiles mod. Either way, I'll add a !=null check for this

**Comment by BigBastard** [comment]
Should be fixed as of build 119:
https://jenkins.ironhide.de/job/Valkyrien-Warfare-Revamped/119/

Let us know if the problem persists
