### ISSUE TITLE
Crash with PhysicsTickHandler & CallRunnerClient

### ISSUE THREAD

**Issue by Johncjx** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#78]
forge version :1.10.2-12.18.3.2254
mod version:ValkyrienWarfareRevamped-1.10.2-0.8.7-125.jar
[crash-2017-04-09_00.11.29-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/907632/crash-2017-04-09_00.11.29-client.txt)
[crash-2017-04-09_00.07.06-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/907633/crash-2017-04-09_00.07.06-server.txt)

**Comment by BigBastard** [comment]
Should be fixed in latest Jenkins builds, will update on Curse soon.

https://jenkins.ironhide.de/job/Valkyrien-Warfare-Revamped/126/
