### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Agentx49** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#80]
Exception loading model for variant valkyrienwarfarecontrol:shippilotschair#inventory, normal location exception: 

https://paste.ee/p/snt1p

**Comment by BigBastard** [comment]
A model error wouldn't cause your game to crash. This looks like an issue with OneSixLauncher, not VW.

**Comment by Best108** [comment]
Old issue, closed.
