### ISSUE TITLE
VW Doesn't Cope well when Loading Chunks in WorldGen Intensive Customised Presets

### ISSUE THREAD

**Issue by FactualOrc** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#83]
Issue:
FPS drop, physics lag and overall performance hit when moving a skyship into previously unloaded chunks while using a customised preset that uses settings that taxes the worldgen code

Replication:
I had this problem when using [this preset](http://worldpresets.com/?world_preset=the-edge-a-skylands-world) and [this ship](http://i.imgur.com/Kd0pPS5.jpg)

Observations:
The ship physics had been stuttering slightly most of the time during play and the hovering code was easily put astray i.e. the ship would deviate between rapid ascent and rapid descent

Relevant Logs:
no blatant errors or crashes

**Comment by Best108** [comment]
Old issue, closed. This should be fixed since the physics engine has been moved off the game thread.
