### ISSUE TITLE
Text Does Not Display on in-World OpenComputers Screen

### ISSUE THREAD

**Issue by FactualOrc** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#84]
Issue:
The OpenComputers screens do not display text when in world and on a ship that has had physics enabled, the screen must be activated and the gui appear before text can be interacted with

Replication:
Setup a OpenComputers station on a physics enabled airship, the mod list I was using can be found [here](https://pastebin.com/S7bpkyTa)

Observations:
Other people have reported that the bug has been fixed although I am still experiencing it

Logs:
No blatant errors or crashes

**Comment by BigBastard** [comment]
Strange, it seems to be random as to whether the player sees the screen or not. Not sure what this means though.

**Comment by Best108** [comment]
Old issue, closed.
