### ISSUE TITLE
Super Circuit Maker is Incompatible

### ISSUE THREAD

**Issue by FactualOrc** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#85]
Issue:
Circuits can not be created on board skyships

Replication:
Attempt to create a circuit on a circuit plate that is mounted on a physics enabled skyship, the modlist I was using can be found [here](https://pastebin.com/S7bpkyTa) the predominate modpack is Infinity Lite but it has been moderately chopped and changed

Observations:
Not even blueprinting a circuit onto the plate worked, the plate was completely disabled

Logs:
No blatant errors or crashes

**Comment by Best108** [comment]
Old issue, closed.
