### ISSUE TITLE
Better with mods Pulley system broken by Valkyrien Warfare

### ISSUE THREAD

**Issue by Octopork** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#86]
[Issue on BWM issue tracker for reference](https://github.com/BeetoGuy/BetterWithMods/issues/302)

Issue in question 
> Pulley not 'pulling' rope up. #302
> Whenever i activate a pulley to pull(hope I'm making sense there) it deletes the anchor, platforms and last rope then proceeds to do nothing but flood my console with:
> [STDERR]: [betterwithmods.util.AABBArray:func_72321_a:225]: AABBArray.addCoord() is stub
> [STDERR]: [betterwithmods.util.AABBArray:func_186664_h:231]: AABBArray.contract() is stub
> 
> Even after deactivating or destroying the pulley.

thanks to a number of issues detailed in the comments a fix is not possible from their end.

Better with mods version:0.14.22 Beta
Valkryien warfare versions 8.9999 stable(curseforge 1.10) and jenkins build No. 27 on 1.11

Note: this isn't occurring when using the pulley on an airship, it's occurring when Valkyrien Warfare is simply loaded.

**Comment by Best108** [comment]
Old issue, closed. I hope this issue doesn't occur in the latest version.
