### ISSUE TITLE
Single Player Ships deleted when moving map to Forge Server.

### ISSUE THREAD

**Issue by DrakeEldridge** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#91]
I tried to move my SP map to my Forge Server but it deletes Elevators from Thuttech and the Ships from this mod (ValkyrienWarfare) 

Might be sponge?
Log is filled with Fixed block id mismatch
Here are the logs: 
[logs.zip](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/950432/logs.zip)

**Comment by Best108** [comment]
Old issue, closed.
