### ISSUE TITLE
Crash w/ onDrawSelectionBox

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#94]
Forge 2254-1.10.2
Valkyrien Warfare v0.8.999 Stable
I got this crash upon right-clicking the ship creator. There was a plain, black banner, [Grimpack](https://minecraft.curseforge.com/projects/grim-pack) mod fans, and a [Mr. Crayfish Furniture](https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod) mod oak chair included on the ship, just in case these had something to do with the crash.
[Crash Report](https://pastebin.com/RhMkWV4i)

**Comment by WenXin20** [comment]
The Grimpack mod fans also still seem to create massive lag on the ship.

**Comment by Best108** [comment]
Old issue, closed. This shouldn't occur in the latest version.
